### ISSUE TITLE
Error in nlsModel(formula, mf, start, wts): : singular gradient matrix at initial parameter estimates

### ISSUE THREAD

**Issue by cummins070** [facebookexperimental/Robyn#101]
# Contributing to FB NextGen MMM R script

# Issue

Hi there,

I'm getting the below error when tryin to run "dt_mod <- f.inputWrangling()"

Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates

**Traceback:**
10.
stop("singular gradient matrix at initial parameter estimates") 
9.
nlsModel(formula, mf, start, wts) 
8.
nlsLM(exposure ~ Vmax * spend/(Km + spend), data = dt_spendModInput, 
    start = nlsStartVal, control = nls.control(warnOnly = T)) at fb_robyn.func.R#342
7.
withCallingHandlers(expr, warning = function(w) if (inherits(w, 
    classes)) tryInvokeRestart("muffleWarning")) 
6.
suppressWarnings(modNLS <- nlsLM(exposure ~ Vmax * spend/(Km + 
    spend), data = dt_spendModInput, start = nlsStartVal, control = nls.control(warnOnly = T))) at fb_robyn.func.R#342
5.
value[[3L]](cond) 
4.
tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
3.
tryCatchList(expr, classes, parentenv, handlers) 
2.
tryCatch({
    nlsStartVal <- list(Vmax = dt_spendModInput[, max(exposure)/2], 
        Km = dt_spendModInput[, max(exposure)])
    suppressWarnings(modNLS <- nlsLM(exposure ~ Vmax * spend/(Km +  ... at fb_robyn.func.R#332
1.
f.inputWrangling() 

# Steps to Reproduce

I'm using my own data, with "clicks" for all the mediaVarNames. 

# Environment
R-studio 

R version (R --version)
4.1.0 (2021-05-18)

Any help would be greatly appreciated!

**Comment by gufengzhou** [comment]
Hi, I assume you ran the script with simulated data successfully, but failed with your own data, right? This is because of the difficulty of the Michaelis Menten fitting to find starting values. I'll fix this in the next update. Until then, there's an inelegant way to solve it: Please try removing your media variable one by one to find out which causes the error. When you find it/them, please use spend (instead of clicks) for now to avoid the error. After the update you should be able to use any clicks as you want. Sorry for the inconvenience.

**Comment by cummins070** [comment]
Correct, it ran fine with simulated data but failed with my own data. Thanks for the response, I will try this and let you know how it goes!

**Comment by gufengzhou** [comment]
let me know if you have more issues
