### ISSUE TITLE
Impressions/GRP vs Spend

### ISSUE THREAD

**Issue by mshors81** [facebookexperimental/Robyn#107]
In the comments for media variables it says "we recommend to use media exposure metrics like impressions, GRP etc for the model. If not applicable, use spend instead"

What is the reasoning behind the recommendation?  Is there a need to be consistent across channels?  What importance is the demographic of the impressions?

**Comment by Leonelsentana** [comment]
Hi mshors81,

Hope you are well and thanks for your interest in Robyn. Media metrics that reflect ad exposure are always preferred. E.g. Impressions, GRPs, etc. This is because they reflect the actual mix between reach and frequency of ad exposure to your marketing audience. When we talk about spend, pricing comes into place and most channels have varying costs per impressions, GRPs, etc.. Some even require closed negotiations that may not linearly behave and reflect the ad exposure on users per se. E.g. Buying TV ads during super bowl vs. low season, you may need much more spend during super bowl in that case to reach out to the same audience at the same frequency than during low season. Said that, we always require people to input spend because of course, we translate back any media variables (Impressions, GRPs, etc.) to ROI using a non-linear model called michaelis-menten or linear models depending what is the best fit for the relationship between media spend and media ad exposure metrics.

Hope it helps,
Thanks! 
Leo

**Comment by gufengzhou** [comment]
let me know if you have more issues
