### ISSUE TITLE
Response Curve and Mean Spend by channel calculation

### ISSUE THREAD

**Issue by Ocean199** [facebookexperimental/Robyn#109]
Great work.  

I have one question with regards to the Response Curve and Mean Spend by channel plots.  Is the spend the raw spend or extrapolated spend factoring adstock and saturation?  If raw, are the responses mapped back to the original day spend?  For instance, once the adstock and saturation is applied, responses from the raw spend on X1 may be from the next day X2. If so how is the saturation accounted for?  As the top of the curve will receive less responses then the bottom, which day is more saturated?

Thanks

**Comment by gufengzhou** [comment]
Hello, a great question you're asking. The response curve itself is generated with the adstocked spend, which are the curves you see in the plot. Or to be precise: response of var1 = coef1 * saturated(adstocked(spend_var1)). However, the mean spend  point is calculated with the raw spend. Why using raw mean spend, not saturated mean spend? Because raw spend is steerable, saturation not. 

Regarding the question "which day is more saturated", if you mean where is the lowest marginal return, well for a C-shape curve it's just the highest point on the curve. For a S-shape curve, it could be beginning or the end of the curve.

**Comment by Ocean199** [comment]
Hello,
Thank you for your response.  I'm still trying to understand how the curve is generated, particular the spend axis.  You mentioned using the raw spend.  When I look at the code, I see the table is generate by

dt_scurvePlot <- cbind(melt.data.table(dt_transformSaturationDecomp, id.vars = "ds", variable.name = "channel",value.name = "response"), melt.data.table(dt_transformSaturationSpendReverse, id.vars = "ds", value.name = "spend")[, .(spend)])

dt_transformSaturationSpendReverse is the Spend axis, but this doesn't appear to be the raw spend, does this apply the adstock and saturation?

![image](https://user-images.githubusercontent.com/87148058/125539374-54827cd9-ff0d-4e31-8417-7c18a8c074d5.png)

When I look at the chart, can I say if I spend X I will get Y responses?  But it seems to me, i would need to apply the adstock and saturation effect to my spend in question to cross reference the chart

Thanks

**Comment by gufengzhou** [comment]
Yes, dt_transformSaturationSpendReverse is adstocked. It's called spend reverse because there're cases where you have impressions adstocked, then I have to reverse it to spend. The curve itself is exactly produced by the hill function. If you look at the f.transformation function, you see how it's done: 1. adstock, 2.normalisation (deprecated), 3.saturation. The saturation step produces this curve. 
![image](https://user-images.githubusercontent.com/14415136/125621750-1035c1cd-edd8-4c2c-87e3-3d39b5c2be59.png)

I know this is confusing. So let me explain it with an example. The entire flow looks like this: 
1. raw spend --> 
2. adstocked spend by geometric or weibull function --> 
3. saturated spend by hill function--> 
4. fitting to get coefficient --> 
5. channel effect = saturated spend * coef
As said before, the curve itself is just the shape of hill function. If you put point 2 above adstocked spend on x-axis and point 3 saturated spend on y, you will see the saturation curve already, same shape as using point 5 channel effect on y-axis, just the scale of y-axis is different. Or in other words, the difference between 3 & 5 is just the multiplication of coefficient that is a constant. It doesn't change the hill transformation at all. 

Now to your question "When I look at the chart, can I say if I spend X I will get Y responses?". First of all we have to separate the prediction result from modelling result. The modelling result (from f.robyn()) includes the response added by adstocking, while the prediction result from f.budgetAllocator() doesnt. 
Let's say you spent 100$ this week and get 20$ adstocked from last week, then you'll have a total adstock worth of 120$ this week. Again assuming you got 240$ back as effect for this week after the modelling, so you have an ROI of 2. This is the modelling result. 
Then you ask for prediction: "if I spend 100$ again, what response will I get?". Can I say you'll get 240$ back? Can I, or should I, always assume there's 20$ worth of adstock from the history? We think it's difficult to assume that. Imagine if you pause the channel 10 weeks and then spend 100$ again, you'll have maybe only 1$ adstocked; if you pause 1 year, then there'll be almost 0 value adstocked, right? Also another question is should we assume the same adstock rate for the future? That's why when doing prediction, we choose to be conservative and rather understating the effect than overstating it: for 100$ spend, we don't assume it'll become 120$ or 101$ after adstocking, it's just 100$. You'll get maybe 210$ response back, but not 240$. 
Finally, where is the 100$ located on the curve? Well, it's just where x axis == 100$ and y axis == 210$ is. You can also see it as the short term effect when doing prediction/ reallocation. Hope it makes sense.

**Comment by Ocean199** [comment]
Make sense, I think the part about measuring the short term effect puts a bow on it.   In the example of the $100 spend after a dark period, I hadn't expected an adstock from previous days to be included, but for the adstock to future days to be included i.e my $100 this week gets me an extra 30 next week and so on.  But if I am reading your reply correctly, it is not included because its the short term effect rather then "fully baked".

**Comment by gufengzhou** [comment]
What you mean by "adstock to future days" is forecasting. Robyn doesn't have forecast capability yet. It's "just" prediction based on historical saturation relationship.
When using weekly data, the saturation curve is always average weekly saturation. Likewise for daily data. But this is not what makes it short term. It's short term because we don't consider adstocking when doing prediction. Moreover, there's no agreed way to capture longterm response in MMM so far. Adding adstock onto the raw data before regression might even reduce the effect of variables sometimes by messing up the correlation. We're also still researching to be honest.

**Comment by Ocean199** [comment]
Hello,
I meant by "Adstock to future days", if my initial spend is $100 with an adstock decay of .3, the total effect is $142, $100 X0, $30 X1, $9 X2 ...  (sum(stats::filter(x=c(100,rep(0,100)),filter=.3,method="recursive"))).

It appears based of your response "put point 2 above adstocked spend on x-axis" this is what your x-axis on the response curve is.  Therefore if I want to cross reference $100 in raw spend, I would have to apply the function above and cross reference $142 on the x-axis rather then $100.

 You really lost me on your comment "Adding adstock onto the raw data before regression might even reduce the effect of variables sometimes by messing up the correlation", but isn't this what you are doing 
![image](https://user-images.githubusercontent.com/87148058/125688052-3355694a-8e20-4a03-b055-a67894ba8076.png)

Thanks

**Comment by gufengzhou** [comment]
ah ok, it's the infinit sum of geometric series, so 100 * (1/ (1-0.3)) = 142. Well then you're right about referencing 142$ on x-axis instead of $100 to include all future adstock. Although this only works for geometric series. For weibull it'd be probably some approximation hat takes a bit longer. Thanks for raising this. We'll discuss how we treat this again.
The last thing with adstocking & correlation: adstocking is essentially data manipulation. Esp. with strong adstocking, the time series might look quite different afterwards. We know that the correlation between each indep.var and dep.var is an indicator of the indep.var's contribution in the regression result. We've seen cases that the correlation reduces after very strong adstock transformation, which led to reduction in effect.

**Comment by Ocean199** [comment]
Thank you so much, one other thing if I may.  

I could be wrong but it looks like in order to get the spends for the x-axis, you are deriving them from the adstocked exposures (dt_transformAdstock), using the "reverse Michaelis Menthen".  

![image](https://user-images.githubusercontent.com/87148058/125839327-befe1fb4-43a0-45af-9992-b1ef1a936d56.png)


However aren't the values from the modNLSCollect obtained using the raw media and raw spend?

I noticed when  applying a highly adstocked variable, the results can get extreme.  Shouldn't the modNLSCollect be calculated off the adstocked media to raw spend relationship?

**Comment by gufengzhou** [comment]
you're very right there. probably that's the better way to do it after adstocking. we've chosen to do it before for 2 reasons:
1. The biggest reason is better performance. doing it after adstocking means it happens in every iteration, while doing it before is just once for all
2. Let's say it's impression as exposure metric. The way we do it now is fitting modNLS with raw spend and raw impression. When doing reverse, it's from adstocked impression to adstocked spend. Because the adstock transformation is the same for imp and spend, the spend-exposure fitting should be still ok. Example, let's say we have 3 spend points: 10, 20 & 30$ and let's assume a linear relationship between spend - imp for easy calculation now, let's say we have coef. of 10, or 1$ gets 10 imps, then we'll have 100, 200 & 300 raw imps. With 20% decay, adstocked spend is 10, 22, 34.4$, while adstocked imp is 100, 220 & 344 imps. You can see that the relationship doesn't change before and after adstocking.

**Comment by Ocean199** [comment]
I was thinking from a NLS (Michaelis–Menten) standpoint, the results would be incorrect because the Vmax and Km, would not be the same after Adstocking.

**Comment by gufengzhou** [comment]
Yes you're right about that fitting MM on raw spend to raw imp will result in different Vmax/Km than fitting it on adstocked spend & adstocked imp. But this is actually only used in the budget allocator to reverse imp to spend and we believe it's rather a philosophical question of thinking about the spend you input into the allocator is representing the raw spend only or it also includes the decay effect/inifinit sum of that spend. In fact, esp. when the solution to long-term effect is not clear yet, we believe it's easier to think of that allocator input just as raw spend. Also, reverse-adstocking is quite difficult to do and it will "ruin" the shape of the final response curve. These are the reasons why we do it this way. However you're of course welcome to implement any changes on your end to do what's reasonable to you.
