### ISSUE TITLE
Allocation showing "off holiday" as a constant

### ISSUE THREAD

**Issue by Ocean199** [facebookexperimental/Robyn#112]
Hello,
I was running Robyn on real data and I noticed the absence of a holiday is receiving a constant allocation almost like an intercept.  I was wondering if this was intended?

![image](https://user-images.githubusercontent.com/87148058/125667402-ac960b9f-e6ca-4909-9e75-19e8f48381c3.png)

 Obviously when there is a holiday it adds or subtracts the value of the holiday

![image](https://user-images.githubusercontent.com/87148058/125667542-3100c4c2-a83b-4c9a-8ed2-7965410f3191.png)

Thanks

**Comment by gufengzhou** [comment]
This is partly because I rescale trend/season/weekday/holiday to positive after prophet decomposition. What happens here is basically your holiday has got the effect from intercept. So you're right about that. Therefore it might be helpful to look at the effect of all non-media/baseline variables together

**Comment by Ocean199** [comment]
Awesome, thanks
