### ISSUE TITLE
Timespan to consider to fit the model

### ISSUE THREAD

**Issue by LeoUbbiali** [facebookexperimental/Robyn#113]
Hi,

I’m raising this issue to ask for advice on the timespan of historical data to consider when fitting the model.

My understanding is that there's potentially a trade-off between the length of the dataset (weeks/days) and its relevance.
- **Lenght:** the more datapoints we have the better the model will fit ceteris paribus ( _i.e._ we can add prophet-based variables)
- **Relevance:** the marketing mix N time periods ago may be completely different than the most recent one ( _i.e_ in the last 6 months) with channels that are not active anymore

I'm eager to hear your thoughts on this - is there a general guideline you would recommend with Robyn?

**Comment by gufengzhou** [comment]
Hi, so far it's still quite arbitrary to say how long timespan is optimal. But we know that the trend is moving away from traditionally years of weekly data towards <1year daily data. We believe between 6 -12 months (180-360days) is a good size, because it reflects your most recent activities, thus more relevant insights. However, variables like trend, seasonality & holiday can still benefit from longer period. Therefore, what we're trying to do in the next update is derive trend from all data, while enable shorter period for modelling. Hope it helps

**Comment by LeoUbbiali** [comment]
Thanks Gufeng for the thorough reply. It helps.
Looking forward to the next update. Do you guys have a rough timeline for it yet?

**Comment by gufengzhou** [comment]
You're welcome. It takes longer than expected and we're now looking at mid-august
