### ISSUE TITLE
Vastly Different Paretos

### ISSUE THREAD

**Issue by Ocean199** [facebookexperimental/Robyn#114]
Hello,
I have been running Robyn over the past couple of days and while I understand models outputs can vary, I am seeing vastly different search spaces between runs. No changes in data or settings.

![image](https://user-images.githubusercontent.com/87148058/125987635-e9c9af5d-2495-4154-9e9f-e4cbc903de58.png)

The blue was run first  (100 trails and 500 iterations) and the pink after (300 trails and 500 iterations), on the aggregate, the model pools have vastly different results

Any insights would be appreciated

Thanks

**Comment by Ocean199** [comment]
Hello,
I thought it might be interesting to show, I just ran 40 trails of 500 interations (yellow) using RandomSearch
![image](https://user-images.githubusercontent.com/87148058/125991328-57905c8a-0faf-48ea-b80d-283456b4021e.png)

Seems to have more balanced results

**Comment by gufengzhou** [comment]
Hey, this is super interesting, thanks for sharing this!  Although we're aware that different algo will have different behaviours, I'm still a bit surprised that the difference is so obvious. This is actually the reason why we do different trials instead of just 1 trial with large iterations, because we wanted to get different initialisation of the random walk in Nevergrad. I'll ping this back to Nevergrad team to see what they say. 

At the same time, are you still able to get similar groups of results with these different runs? I mean if the effect shares, decays etc are comparable? Because in the end that's what matters for MMM, right?

**Comment by Ocean199** [comment]
Hello, The results can be quite a bit different depending on the Algo.  From left to right on the below chart are two DiscreteOnePlusOne runs, then the RandomSearch. Sales channel E, which is a high spend channel (15%) ranges from a 0 ROAS to a ~4 ROAS.

![image](https://user-images.githubusercontent.com/87148058/126810882-48788c9a-8604-4931-abf6-88b88c9d5cc3.png)

I ran a few more runs with other Algos

![image](https://user-images.githubusercontent.com/87148058/126812268-cc38c3c2-0432-407e-8447-50f178a5e42c.png)

Green and Blue are DiscreteOnePlusPne.  Red is TBPSA, Yellow is TwoPointsDE.  I am not familiar with the differences between the algos, I random choose them, but the Red and Yellow seem more optimal.

ROAS results:
![image](https://user-images.githubusercontent.com/87148058/126812722-92a2c2e2-7dd6-4b95-b862-7835ce039d01.png)

Channel E still is jumpy, ranging from 0 to ~2 ROAS

**Comment by gufengzhou** [comment]
Hi, thanks very much to sharing this very interesting result. I've talked to team Nevergrad and we'll implement an improvement to have better initial step size when starting Nevergrad (and this will also eliminate the "bounds are 1.0 sigma away" warning). We believe this improvement will result in faster convergence across all algos. 
Regarding the "jumpy" behavior of some channels' ROAS, I understand the expectation to seeing convergence there. However, it's actually intented to have different, but non-extreme choices on channel ROAS so that users can choose. For your example, I think ROAS from 0-2 is kind of a "realistic" range, I'm glad it's not 0-20. In the end, which model result to choose remains a subjective task. We recommend to look for other measurement results to guide the choice. Best options are experiments (GEO test, FB lift test etc.). But also previous MMM results (maybe from 3P providers? inhouse model?) or even MTA could be source of truth, as long as you have faith in the result.

**Comment by Ocean199** [comment]
great, thanks
