### ISSUE TITLE
Robyn doesn't give me positive coef for my media variable

### ISSUE THREAD

**Issue by retiuk** [facebookexperimental/Robyn#115]
Hi FB Team,

I got this media variable. When I define it's sign to be positive in 'set_mediaVarSign', the model just drops the variable (coef = 0).

I tried defining it negative sign to see what happened and it comes into the model with negative coefficient, but of course this is not expected as it's own investment.

The spend for the variable is quite significant, so I can't really tell the client it's driving zero volume.

I checked and the Pearson correlation is slightly negative with sales (execution peaks at a time where sales are low, and does not execute at time where sales are high). I assume this might be the issue from a start as the model is linear.

Do you have any suggestion?

Many thanks!

R

**Comment by gufengzhou** [comment]
Hi, I think you should maybe look at the issue bit differently. Robyn cannot guarantee an effect, because in a regression model, correlations between the dep.var and the indep.vars are the foundation for any effect. If this channel has very weak correlation to sales, the regression model can't give you effect "magically". 
However, you can still do something about it. We recommend the following when an important variable is not showing effect:

1. First thing to do is look at correlation matrix with sales. If the important channel is having weak correlation anyway, consider split media into sub-channels, and/or aggregate similar channels
2. Increase hyperparameter ranges for 0-coef channels on theta (max.reco. c(0, 0.9) ) and gamma (max.reco. c(0.1, 1) ) to give Robyn more freedom. Although this might lead to difficult interpretation if you're not expecting high decay for this channel
3. Increase trials to get more samples

**Comment by retiuk** [comment]
Hey thanks really valuable your inputs as always!
