### ISSUE TITLE
Channel seasonality performance

### ISSUE THREAD

**Issue by madnoodles** [facebookexperimental/Robyn#116]
I'd assume we consider the correlation to be stable across the year but in reality channels also might have it's own seasonality.
How would you consider include channel seasonality performance?
For example, if I'm modeling spend vs users acquired, and in the beginning of the year some channels might be cheap while the cost start trending up in the summer.

**Comment by gufengzhou** [comment]
Hi, you're right that every variable has its own seasonality. However when predicting sales in Robyn, we're only explaining sales with media vars, trend and season and others. The fact that a certain channel's CPA might be higher / ROAS lower during xmas is handled by the saturation curve. We're not trying to explain the media spend. Does it make sense?

**Comment by madnoodles** [comment]
Thanks for the quick reply. How does saturation curve handle seasonal change? From my understanding saturation curve is about spend effectiveness and to understand the elasticity of the spend, right? So if we spend same amount of money we will get same respond from the curve, while channel own seasonality means with same level of spend we are getting more or less because of seasonality(like you said xmas period might be more expensive).

**Comment by gufengzhou** [comment]
sorry for late reply. you're right that saturation only takes care of elasticity. first of all, Robyn predicts sales using media, so the seasonal effect from media to sales is modelled already. If there's any spending pattern of your marketing activity, for example always spending more money around xmas, this will help explaining sales along with the seasonal variable. 
Regarding "media's own seasonality",  if you mean the purchase price like cpm or cpc, it's not accounted for in Robyn, because we're not trying to explain media itself. When using impressions for FB as example, we do model the relationship between FB spend and impressions using a simple michaelis menten function, which models the elasticity of FB spend & imp, but not seasonality. I can imagine it'd probably be helpful to have better spend-imp prediction, but it will "ruin" things a lot for Robyn's saturation curve that's from hill function, which again will make budget allocation impossible. So all in all, it's rather out of practical reason that we're not also modelling media seasonality

**Comment by gufengzhou** [comment]
please re-open if necessary
