### ISSUE TITLE
Calibration using experiments for Matched Markets

### ISSUE THREAD

**Issue by amogh-nalwaya** [facebookexperimental/Robyn#129]
In the calibration using experimental results example, we see the variable `liftAbs` as measuring the absolute lift in the response variable.

`
set_lift <- data.table(channel = c("facebook_I",  "tv_S", "facebook_I"),
                       liftStartDate = as.Date(c("2018-05-01", "2017-11-27", "2018-07-01")),
                      liftEndDate = as.Date(c("2018-06-10", "2017-12-03", "2018-07-20")),
                    liftAbs = c(400000, 300000, 200000))
`

Let's say our response variable was measured at the national level. Some experiments were run for certain matched markets with the lift measured at the market level - a lower scale of magnitude than the national level. Would it be possible to somehow include the experiment market exposure size in order to normalize the measured lifts in calibration?

Hope that makes sense.

**Comment by gufengzhou** [comment]
Hi, sorry for replying late. This is a bit tricky. Let's say you want to calibrate FB. Ideally you should have experimental result for the same spend as your FB variable in the model. Now you might have two options:
- Splitting the FB variable in the Model from national to market Level and thus match the campaign scope on market level
- Extrapolating the market level experimental results up to national level to match the scope on national level

I'd recommend the first option because by splitting variables, you will get more granular insights too. Hope it helps.

**Comment by amogh-nalwaya** [comment]
@gufengzhou Thank you for the recommended options. The data does not have reliable media spend information at the market level so at this point, the second option looks to be our only choice. Extrapolation can blow up the non-spend variables so we will have to think about the right way to do that.

**Comment by gufengzhou** [comment]
please re-open if necessary
