### ISSUE TITLE
Decomposition Distance

### ISSUE THREAD

**Issue by TimKreienkamp** [facebookexperimental/Robyn#135]
Hi Facebook colleagues, 

amazing package!

While digging deeper into the specifics, I was wondering how the decomposition distance is calculated, what is the rationale behind it and how you decide which pareto-optimal solution to pick when weighing MAPE against decomposition distance?

Thanks in advance!

Tim

**Comment by gufengzhou** [comment]
Hey, thanks for trying it out! For the decomposition distance, please see [here](https://github.com/facebookexperimental/Robyn/issues/82). Regarding the model selection, Pareto optimality gives you the best options trading off model fit (NRMSE) and business fit (DECOMP.RSSD). But you're still getting a set of results and need to decide which one to pick. It's our decision to leave users these choices so that is not a blackbox solution. Selection guide could be:

- Experimental results (FB lift, Geo test etc)
- previous MMM results that are considered good fit
- any attribution results that are considered good fit. 

In the end, we believe experiments and calibrating the model using experimental results is the way to go. Hope it helps

**Comment by gufengzhou** [comment]
please re-open if necessary
