### ISSUE TITLE
Using spend as variable

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#138]
# Expected Behavior

In your guide [here](https://facebookexperimental.github.io/Robyn/docs/step-by-step-guide/) is it correct that you have the spend for some channel as a `set_mediaVarName ` variable e.g that `tv_S` is the spend for tv ?
 
```
set_mediaVarName <- c("tv_S"    ,"ooh_S",   "print_S"   ,"facebook_I"   ,"search_clicks_P")
set_mediaSpendName <- c("tv_S"  ,"ooh_S",   "print_S"   ,"facebook_S"   ,"search_S")
```
What is the impact/purpose of having/not having the spend e.g `tv_S` as a mediaVar? Is it when we don't know the "outcome" say impressions, clicks etc. but we do know our spend?

Furthermore you write that it's a naming convention to let the spend-variables end with `_S` e.g `tv_S`. Do they all have to do that or could we call it e.g `tv_spend` instead?

**Comment by gufengzhou** [comment]
Hi, thanks for using this! The reason behind using exposure metrics (imps, clicks, GRP etc.) instead of spend is that we believe exposures better represent your paid media pressure at the audience, whereas spend has different efficiency across channels, or sometimes even within one channel. For example, 1 dollar spend on channel A might yield different reach as 1 dollar on channel B. Or FB retargeting campaigns and FB prospecting campaigns might very likely have different CPMs. We think that it makes sense intuitively. However, we can't quantify and verify this claim with numbers yet because we don't posses real client data. Hope it makes sense.

Regarding the naming convension with "_S", it's an old information and not necessary anymore. We'll update the guide soon.

**Comment by Jakobhenningjensen** [comment]
Thanks a lot!
