### ISSUE TITLE
What does the "wings" in the hyperparameter plot show?

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#144]
# Contributing to FB NextGen MMM R script

# Issue

Looking at the following plot

![image](https://user-images.githubusercontent.com/37367467/130792657-6bfeccba-47ed-4016-9534-88fdfdf9bfd1.png)

what does the wings tell us? I would assume some sort of confidence interval but I cannot make that sense, since it's a 1D plot. Is it a density-measure i.e we have more points in a "wing" area than not?

I assume the plot is for chosing a suitable range for each parameter i.e if don't see a lot of points above, say 2, for the alphas, then we can reduce the upper-limit to 2.

**Comment by Jakobhenningjensen** [comment]
That is completely understood that it's the sample-space. I just wonder if the curve/wings showed either more/less points in that area (i.e density, as you explain).

I understand that we set the hyper-parameters manually, but I assume that the plot is used for getting an overview of the space of which each paramater is sampled from? I.e if we have a lot of points between (0,0.3) and only two points between (0.3-1) for e.g gammas, whouldn't that be an argument for running the model again, but restraining gammas interval to (0,0.3) instead of (0,1)?

**Comment by gufengzhou** [comment]
Now I get what you mean. Good one. If range is 0-1 but it only explores 0-0.3, it could mean that the sampling has started in 0-0.3 area and converged early. Because we know that our hyperparameter optimization problem is very likely to have multiple local minimum, the fact that it converged early within 0.3 doesn't mean it'd be the best globally within 0-1. That's why we do multiple smaller trials instead of one big trial with more iterations to better explore the entire space. But if every trial already explores the whole space and always end in one certain area, then it's a clear sign of global convergence. This behavior will be clearer in the coming release end of Sep.

**Comment by Jakobhenningjensen** [comment]
Indeed we might run into local-optima.

Just to be completely clear; when you say a "sample" do you then mean the last sample after a trial has converged/finished i.e the best sample from the trual or is it all samples within a trial? Say a trial runs for 100 iterations, do we then get 100 sample points for each parameter or just 1 for that trial?

**Comment by gufengzhou** [comment]
It'd be 100 in your scenario. One iteration is one sample.

**Comment by Jakobhenningjensen** [comment]
Gotcha - thanks for clarifying.
