### ISSUE TITLE
up-scaling iterations or trials when number of features increases

### ISSUE THREAD

**Issue by Jakobhenningjensen** [facebookexperimental/Robyn#155]
# Contributing to FB NextGen MMM R script

# Issue

The standard settings are 

`set_trial<- 40`
`set_iter <- 500`

As far as I understand, the number of trials is the number of initializations of hyper-parameters, and 500 is then the number of iterations used by Nevergrad, to find the optimal hyper-paramaters (for each of the 40 initializations).

How many iterations are (usually) enough for Nevergrad for convergence and how much is it dependent on the number of features? I.e when increasing the number of hyper-parameters, would it then be better increasing the number of `trials` or the number of `iter`? I would assume that since the parameter-space increases exponentially with the number of features, increasing trials would be better, than increasing the number of iterations.

R version: 4.1.1

**Comment by gufengzhou** [comment]
Great question!

The 500 * 40 recommendation sofar is rather based on gut feeling, because it was very difficult to quantify it before we've fine-tuned Nevergrad. In the upcoming release, the reco will be changed to 2000 * 5 based on the following:

This plot shows algo comparison with 500 * 10. The two DE algos are achieving lowest combined error, and it looks like they will further converge. 
 ![image](https://user-images.githubusercontent.com/14415136/132462469-3a643162-6b0e-493f-b76d-8476f4c1e1e9.png)

This shows the comparison between the two DEs with 2000 * 5. It shows that after about 1k the convergence is more obvious. Also the 5 trials seem to be similarly low. We've decided for TwoPointsDE & 2k * 5 in the end. 
![image](https://user-images.githubusercontent.com/14415136/132463298-3cbbd437-45fc-4d1b-92a2-468aab4c274f.jpeg)

This is based on the simulated data. If adding more features, I'm afraid we don't have enough real data to test convergence. Also according to team Nevergrad, there is no perfect way to predict iterations needed. I'd recommend you to test it yourself.
