### ISSUE TITLE
Share of effect as zero

### ISSUE THREAD

**Issue by el-wrk** [facebookexperimental/Robyn#160]
# Contributing to FB NextGen MMM R script

# Issue

When I run the analysis on data from a certain year/market the models are finding share of effect on multiple channels as 0, when I wouldn't expect this to be the case e.g. paid search and display as shown below. What would you suggest to do in terms of validating the truth of these results or better calibrating the models?

![image](https://user-images.githubusercontent.com/87646044/134001621-20eb05a0-b9d0-45de-9d8c-ced7307fda31.png)

# Environment

Robyn 2.0

**Comment by Leonelsentana** [comment]
Hi @el-wrk ,

Hope you are well and thanks for reaching out. Some questions to understand the type of data you are using:

- Is your data granularity daily or weekly? If daily, are you using the "weekday" parameter in prophet?
- How many years of data do you have?
- Have you had stable non-zero investment in all channels on each week or day since day 1?
- If you have periods with zero investment, when do those happen? Is it mostly at the beginning or just spread along the time series period? What's the percentage of blank data points (Where there is no investment in the channel?)?
- Are you using impressions, clicks or just spend for your channels?
- How many trials (set_trials) and iterations (set_iter) do you have? Minimum is 500 iterations and 40 trials.

Thanks!

**Comment by el-wrk** [comment]
Hi, I'm good thanks, hope you are too.
	
• Is your data granularity daily or weekly? If daily, are you using the "weekday" parameter in prophet? **Daily, and no.**
• How many years of data do you have? **I have 2 years overall (2019 - 2020) data and am currently running the years separately due to concern about the effect of COVID on the sales data/model. I've found if I run the data all together the NRMSE is higher.**
• Have you had stable non-zero investment in all channels on each week or day since day 1? **For the most part yes, there are a couple of channels which are more sparse.**
• If you have periods with zero investment, when do those happen? Is it mostly at the beginning or just spread along the time series period? What's the percentage of blank data points (Where there is no investment in the channel?)? **For email and referrer it's more the occasional period of time (a couple of weeks or so) without investment at times within the year. There's a 9.92% null/0 rate across the dataframe, this is mostly concentrated in a couple of channels.**
• Are you using impressions, clicks or just spend for your channels? **I'm using visits to a website attributed to each channel instead of spend.**
• How many trials (set_trials) and iterations (set_iter) do you have? Minimum is 500 iterations and 40 trials. **I was originally running with that number but decreased by about half (250/20) to shorten run time and experiment (no idea why run time is so long for me, I found with 500 iterations a single trial took about 20 minutes to run, so with 40 iterations an overall run time of about 12 hours).** 

While having a look at the data I realised I'd dropped a fairly important channel, so reran and getting a much more sensible result (see below), but still interested to know if you have any recommendations. 

![image](https://user-images.githubusercontent.com/87646044/134188802-f2aa6beb-b582-42e3-8957-896f50296782.png)

Thanks!

**Comment by el-wrk** [comment]
Regarding the attributed data: it's attributed in terms of last touch channel being used to understand where someone is visiting a website from (via which ad channel), not attribution between visits and sales. Otherwise we don't have a reliable way of understanding which channels are doing what: our spend data is unfortunately not great. Is that an issue?

Looking forward to version 3.0! I think I'll wait until the launch to do more testing for now - the results are definitely looking better, thanks for your help.

**Comment by Leonelsentana** [comment]
Hi @el-wrk thanks for coming back to us. It's great to hear that your results are now starting to make more sense with the recommendations I provided. 
As I said, it is not advised to use attributed visits as the main media variable, we recommend using total impressions and spend per channel. Visits sometime may have a bias towards a click-only visit behavior and may be missing the effect of view-trough conversions.
We would love to have you testing v3.0 since Wednesday next week and get your feedback :)
