### ISSUE TITLE
Intercept forced to positive

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#207]
Hi,

While working on understanding the intercept, we found that it is restricted to assume positive values. Thus, model is not allowed to have a negative intercept. What is the reason behind that?

Thank you so much.
Best,
Joan

**Comment by gufengzhou** [comment]
Well spotted. The reason is that, in an additive model, when all terms are 0, intercept represents the "base sales": if not doing any marketing (and also no trend/season etc), this is the revenue you'll make. It's counterintuitive to have negative "base sales". Although one could probably make a case for negative intercept, it's quite usual in MMM do just constrain it to positive. Hope it makes sense?

**Comment by joangcc** [comment]
Hi,

It makes sense. Thanks for your answer!

Best,

Joan

**Comment by shivanichandna** [comment]
Hi,
What if we get intercept as zero? 
We do expect some base sales for our data but what if the intercept is always zero. How do we interpret that?

Thanks,
Shivani
