### ISSUE TITLE
Broken Initial vs. Optimized budget allocation plot and CSV data starting from v3.3.2

### ISSUE THREAD

**Issue by andrey-legayev** [facebookexperimental/Robyn#212]
## Describe issue
We've found that starting from v3.3.2 charts of reallocated budget expense were broken.

I performed some investigation and found that before v3.3.2 SUM(initSpendShare) in *_reallocated.csv files 1.0
But starting from v3.3.2 it has strange values (see screenshot attached)
I was testing it on the same data with the same model configuration, just tried different versions of Robyn from GitHub.

I compared versions in git and found following change # e775ac2cd4d50daa5fd3f0c318fd4f744f0cf8a1
Rolling back the change in R/R/allocator.R fixes the bug.

Could you review if this change introduces the bug?

## Provide dummy data & model configuration
I cannot provide real data for obvious reasons. But I can show comparison of generated PNG and CSV files:
![versions-comparison2](https://user-images.githubusercontent.com/5568564/140815825-fc917147-de00-42e6-8a86-f2e4d8de1804.png)
![CSV comparison](https://user-images.githubusercontent.com/5568564/140815002-93d5ed23-a833-4799-949f-dc395ebe0826.png)

Allocator execution code:
```
    AllocatorCollect <- robyn_allocator(
      InputCollect = InputCollect
      , OutputCollect = OutputCollect
      , select_model = "1_1_4"
      , scenario = "max_historical_response"
      , channel_constr_low = c(0.7, ..., 0.7, 0.01)
      , channel_constr_up = c(1.5, ..., 1.5, 1)
    )
```

IMO there is obvious bug in robyn_allocator() which leads to incorrect values of initSpendShare

## Environment & Robyn version
Robyn MMM versions: v3.3.2 and above (tested up to v3.4.5 including #main branch)
R version: 4.1.1
Platform: Win10

**Comment by gufengzhou** [comment]
hey thanks for spotting this! it's indeed a bug. The change was intended though, just with the wrong variable. The correction is here fca1d04dec69dc2be75941dc354482a223607438

**Comment by andrey-legayev** [comment]
I tested it few times. The plot looked Ok from first look, but there is something still be wrong with data in *_reallocated.csv files: the sum(initSpendShare) != 1
I got following sum value in several models: 0.966, 0.956, 0.966, 0.966 (rounded to 3 digits)

**Comment by gufengzhou** [comment]
These couple of models have paid var with 0 coefficients, right? Then it is intended. For example, if OOH has coef 0, then it has no response and thus is excluded from the allocator. At the same time, the total spend will still include OOH spend. It means the OOH spend will be distributed to other channels. Can you confirm if it's the case?

**Comment by andrey-legayev** [comment]
I need a help:
Where can I look at coefficient for the paid vars? sorry, I'm lost in gammas, thetas and other params.
Is it something we set or something what's saved in the Robyn model (in RDS file)?

Another observation:
Right now ```sum(optmSpendUnit) == optmSpendUnitTotal == initSpendUnitTotal```
But shouldn't it be ```sum(optmSpendUnit) == sum(histSpendUnit)``` ?

The ```sum(histSpendUnit)``` is less than ```initSpendUnitTotal```.
That's why ```sum(initSpendShare) < 1.0``` in my case.

**Comment by gufengzhou** [comment]
No worries. All coefficients can be found either in the pareto_aggregated.csv or OutputCollect$xDecompAgg.
You're asking about hyperparameters (gammas, thetas etc.)? Users set a range and Robyn figures out which values within the ranges are best.

Using the simulated data, I've selected a model that has facebook_I coef is 0 and used it in allocator. Below is the screenshot of output. When I created this table, I've tried to name the columns as intuitive as possible. But apparently it needs more explanations, since some other users are also asking for column definition. Let me do it here and will include it into official documentation in the future.

![image](https://user-images.githubusercontent.com/14415136/141197334-53ea2011-d340-4140-8676-e96aa7ed8d3b.png)

-  $ channels                 : Equals to paid_media_vars. Those with coefficient = 0 are excluded in allocator because it doesn't make sense to optimise 0 response channel. 
-  $ histSpend                : Total spend of each channel within modelling window. 
-  $ histSpendTotal           : Sum of histSpend, including excluded channels. This also represents total historical marketing budget.
-  $ initSpendUnitTotal       : Sum of initSpendUnit, including excluded channels.
-  $ initSpendUnit            : Mean spend of each channel for the respective time grain. Note that the mean is calculated with non-zero spend period. For example, when a new channel has spend c(0, 0, 0, 5, 5), mean spend is 10/2 = 5, because we want mean spend to reflect active spending decision of marketing.
-  $ initSpendShare           : equals initSpendUnit / initSpendUnitTotal. Sum of initSpendShare is <1 when 0-coef channels are excluded.
-  $ initResponseUnit         : Response of initSpendUnit of each channel for the respective time grain.
-  $ initResponseUnitTotal    : Sum of initResponseUnit. Excluded channels don't impact it here because they have 0 response anyway.
-  $ initRoiUnit              : Equals  initResponseUnit / initSpendUnit
-  $ expSpendTotal            : Total marketing budget for optimal allocation. When scenario = "max_historical_response", it equals histSpendTotal. When scenario = "max_response_expected_spend", it equals to user's input in expected_spend argument in robyn_allocator() function
-  $ expSpendUnitTotal        : Total marketing budget for optimal allocation for the respective time grain. When scenario = "max_historical_response", it equals to initSpendUnitTotal. When scenario = "max_response_expected_spend", it equals to expected_spend / expected_days
-  $ expSpendUnitDelta        : Equals expSpendUnitTotal / initSpendUnitTotal -1
-  $ optmSpendUnit            : Optimised spend of each channel for the respective time grain. 
-  $ optmSpendUnitDelta       : Equals optmSpendUnit / initSpendUnit -1. This also reflects the channel constraints in channel_constr_low and channel_constr_up. 
-  $ optmSpendUnitTotal       : Equals sum(optmSpendUnit). When scenario = "max_historical_response", it equals to initSpendUnitTotal and expSpendUnitTotal. However when channel_constr_up is too restrictive, it might be lower that the latter two metrics. When scenario = "max_response_expected_spend", it equals to expected_spend / expected_days. However when channel_constr_up is too restrictive, it might be lower that the latter one.
-  $ optmSpendUnitTotalDelta  : Equals optmSpendUnitTotal / initSpendUnitTotal -1. 
-  $ optmSpendShareUnit       : Equals optmSpendUnit / sum(optmSpendUnit)
-  $ optmResponseUnit         : Response level of optmSpendUnit for each channel
-  $ optmResponseUnitTotal    : Equals sum(optmResponseUnit)
-  $ optmRoiUnit              : Equals optmResponseUnit / optmSpendUnit
-  $ optmResponseUnitLift     : Equals optmResponseUnit / initResponseUnit - 1
-  $ optmResponseUnitTotalLift: Equals optmResponseUnitTotal / initResponseUnitTotal - 1

Finally, to answer your question: sum(initSpendUnit) < sum(optmSpendUnit) when there're channels with 0 coefficients and thus excluded from the budget allocation. For example, assuming you spend total budget of 100$ into TV=70$, OOH=20$ & Search=10$. When OOH has 0 coefficient/ has no response, sum(initSpendUnit) == 80$. But when doing allocation, you still want to spend 100$. So the 20$ of OOH will be split into remaining channels. Hope it makes sense.

**Comment by andrey-legayev** [comment]
Thank you for detailed explanation!
