### ISSUE TITLE
Weibull_PDF: Max Range of Hyperparameters

### ISSUE THREAD

**Issue by RaviP1987** [facebookexperimental/Robyn#218]
Hi FB team

I have an independent variable that is well known to show sales impact in long run. (Exa: activity done today would continue to show sales impact for next 2-3 years). 

My issue is that this variable is showing '0' impact on sales via both weibull PDF/CDF and Geometric. I want to broaden the hyperparameter range and wanted to check what is the max i can go on 'alpha', 'gamma', 'shapes' and 'scale'

Thank you

Regards
Ravi

**Comment by gufengzhou** [comment]
Hi Ravi, very interesting use case. shapes and scales are the two hyperparameters for weibull. Looking at this plot (see either our README on repo or run the `plot_adstock(plot = TRUE)` function), the larger the scale, the longer the carried over effect. We recommend very conservative scale range of `c(0, 0.1)`, because when you have 2 years data, use weibull pdf and has scale of 0.5, it means the peak occurs latest after 1 year, which is quite crazy to me to assume something I do peaks after a year. Also with cdf, you can see that it would mean the peak effect remains a very long time, also very extreme. But of course if you're very certain about this, try it out. 

For shapes, it also very much depend on your prior knowledge. For example you could choose something around 2 for pdf to imitate the slow increase and decrease around peak. For pdf, we recommend to cub at 10 but of course you can go even higher.

There's also a quite thorough explanation in the README as well as in demo.R to guide the bounds selection.

![image](https://user-images.githubusercontent.com/14415136/142185224-b4cae4c4-9dcf-4d0b-88e5-adff28928385.png)

**Comment by RaviP1987** [comment]
Thanks Gufeng for the detailed explanation. I tried increasing the hyperparameter range, but unfortunately it doesnt seem to work.
