### ISSUE TITLE
Understanding spend-exposure fitting warning

### ISSUE THREAD

**Issue by nie-moviestarplanet** [facebookexperimental/Robyn#225]
## Describe issue
After running robyn_inputs I get the following message/warning:
"_Michaelis-Menten fitting for PAID_MEDIA_VAR out of range. Using lm instead
Warning message:
In fit_spend_exposure(dt_spendModInput, mediaCostFactor[i], paid_media_vars[i]) :
  Spend-exposure fitting for PAID_MEDIA_VAR has rsq =  0.323570148129739 To increase the fit, try splitting the variable. Otherwise consider using spend instead._"

1. What does it mean that the PAID_MEDIA_VAR is out of range? What is the expected range? 
2. Can you provide more details about the warning message? Why is it recommended to split the variable use spend to increase fit? 

## Environment & Robyn version
R version (4.1.2)

**Comment by gufengzhou** [comment]
Hi,
1. The out of range error relates to the starting values for the nonlinear fitting for the spend exposure model are somehow not working. It usually happens when the relationship is very linear, in which case it will use a linear model as fall-back. 
2. Imagine you have two different campaigns on FB, one is optimised towards conversions and thus has higher conversion rate, but more expensive CPM. The other is optimised towards awareness and thus has lower CPM, but also worse CVR. When using one single variable to represent FB, the difference above is ignored. When splitting it, not only the spend exposure fitting will become better, but also the total model will benefit from the two new variables that can potentially explain your dependent better. 

Hope it helps.

**Comment by gufengzhou** [comment]
feel free to reopen if necessary
