### ISSUE TITLE
Clarification between "initial avg.spend share" and "spend share" 

### ISSUE THREAD

**Issue by Steven-Livingstone** [facebookexperimental/Robyn#227]
## Describe issue

Hi there,

I've been playing around with your demo example and came across the following that does not make sense to me.

Why are the "spend_share" percentages from the one-pager's "Share of Spend VS. Share of Effect with Total ROI" graph not matching the "initial avg.spend share" percentages from the budget allocator's "Initial vs. Optimised budget allocation" graph?

In my mind, `initSpendShare` should match `spend_share` as they both represent the same spend data _before_ any optimization has taken place. From this [existing issue](https://github.com/facebookexperimental/Robyn/issues/95), I understand your "intention to use [the] mean of non-zero periods as share of spend instead of sum or mean of all periods", yet I can't find a reason why in some cases `initSpendShare` and `spend_share` are so similar (e.g tv_S), yet can also be so different (e.g. search_clicks_P).

Thanks :)

Here are comparative screenshots of the two graphs, as well as the data that generated them:

### Share of Spend VS. Share of Effect with Total ROI

<img src="https://user-images.githubusercontent.com/47679536/144156758-5025e120-3a9f-4653-91e5-11bc3a69ebff.png" height=450>

| rn              | spend_share        | effect_share       | total_spend      |
|-----------------|--------------------|--------------------|------------------|
| tv_S            | 0.311135800761756  | 0.318580217467586  | 10247935.1       |
| search_clicks_P | 0.111321014032676  | 0.122354199544738  | 3666600          |
| print_S         | 0.0848043521333921 | 0.0800224343890439 | 2793216          |
| ooh_S           | 0.310911157955088  | 0.304473301427458  | 10240536         |
| facebook_I      | 0.181827675117088  | 0.174569847171174  | 5988890.41190929 |

_from areto_aggregated.csv_

### Initial vs. Optimised budget allocation

<img src="https://user-images.githubusercontent.com/47679536/144156765-af448461-ff2a-4927-9056-94c348fcee64.png" height=500>

| Channels        | initSpendShare     | optmSpendShareUnit | histSpend        |
|-----------------|--------------------|--------------------|------------------|
| tv_S            | 0.328419507140044  | 0.361261457854048  | 10247935.1       |
| search_clicks_P | 0.0610415255406224 | 0.0671456780946845 | 3666600          |
| print_S         | 0.0994614051084609 | 0.109407545619307  | 2793216          |
| ooh_S           | 0.336597318301676  | 0.305153098913684  | 10240536         |
| facebook_I      | 0.174480243909197  | 0.157032219518277  | 5988890.41190929 |

_from 1_59_12_reallocated.csv_

## Provide dummy data & model configuration
All plots and data have been sourced from the [demo script](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R).

The budget allocation was produced using the following:

```
AllocatorCollect <- robyn_allocator(
        InputCollect = InputCollect
        , OutputCollect = OutputCollect
        , select_model = '1_59_12'
        , scenario = "max_historical_response"
        , channel_constr_low = c(rep(0.9, 5))
        , channel_constr_up = c(rep(1.1, 5))
    )
```

## Environment & Robyn version

```
> sessionInfo()

R version 4.1.1 (2021-08-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /opt/conda/envs/race_mmm/lib/libopenblasp-r0.3.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.22 Robyn_3.4.8    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7         here_1.0.1         lubridate_1.8.0    lattice_0.20-45   
 [5] png_0.1-7          rprojroot_2.0.2    assertthat_0.2.1   glmnet_4.1-2      
 [9] digest_0.6.28      foreach_1.5.1      utf8_1.2.2         IRdisplay_1.0     
[13] R6_2.5.1           plyr_1.8.6         repr_1.1.3         ggridges_0.5.3    
[17] evaluate_0.14      ggplot2_3.3.5      pillar_1.6.4       rlang_0.4.12      
[21] lazyeval_0.2.2     uuid_1.0-3         data.table_1.14.2  nloptr_1.2.2.3    
[25] Matrix_1.3-4       splines_4.1.1      stringr_1.4.0      igraph_1.2.9      
[29] munsell_0.5.0      compiler_4.1.1     pkgconfig_2.0.3    base64enc_0.1-3   
[33] shape_1.4.6        rPref_1.3          htmltools_0.5.2    tidyselect_1.1.1  
[37] tibble_3.1.5       codetools_0.2-18   fansi_0.4.2        crayon_1.4.2      
[41] dplyr_1.0.7        grid_4.1.1         jsonlite_1.7.2     gtable_0.3.0      
[45] lifecycle_1.0.1    DBI_1.1.1          magrittr_2.0.1     scales_1.1.1      
[49] RcppParallel_5.1.4 stringi_1.7.5      doRNG_1.8.2        doParallel_1.0.16 
[53] ellipsis_0.3.2     generics_0.1.1     vctrs_0.3.8        IRkernel_1.2      
[57] iterators_1.0.13   tools_4.1.1        prophet_1.0        glue_1.4.2        
[61] purrr_0.3.4        rngtools_1.5.2     parallel_4.1.1     fastmap_1.1.0     
[65] survival_3.2-13    colorspace_2.0-2   minpack.lm_1.2-1   pbdZMQ_0.3-6      
[69] patchwork_1.1.1
```

**Comment by gufengzhou** [comment]
Very well spotted. It's the subtle difference between share of spend by mean_spend and by total_spend. In the allocation plot, the initSpendShare is generated by mean_spend and serves as starting value for budget allocation. Whereas the previous plot shows spend_share from total_spend. The reason why share of mean_spend != share of total_spend is that we calculate mean_spend from non-zero periods. E.g., var A has spend c(0,0,0,10,10), we consider mean_spend is 20/2 = 10, not 20/5 =4. This causes the difference. We'll align both by changing the first plot to mean_spend too. Thanks for raising this.

**Comment by gufengzhou** [comment]
please reopen if necessary

**Comment by Steven-Livingstone** [comment]
Thanks for the in-depth and enlightening explanation @gufengzhou, and kudos to what you and your team have achieved! 

It does make sense, though the subtle distinction (between inc-zero and exc-zero average calculations) may inadvertently mislead those who don't dive deep into the documentation.

**A follow up question:**

After performing an optimised reallocation, the file `_reallocated.csv` contains the column `optmSpendUnitDelta `

From the [schema](https://github.com/facebookexperimental/Robyn/blob/1095d87d2910c87a50ad545b4888bef57a05cf58/demo/schema.R):
> optmSpendUnitDelta` : Numeric. Equals optmSpendUnit / initSpendUnit -1. This also reflects the channel constraints in channel_constr_low and channel_constr_up

Can this delta be directly applied to `spend_share` from `pareto_aggregated.csv`. I.e. something like the following:

> `optm_spend_share = spend_share * (1 + optmSpendUnitDelta)`

Where `spend_share` is the share of `total_spend`.

Would this, in effect, produce the optimised per-channel allocation % across the entire training period, rather than the optimised budget % for averaged non-zero periods? I agree that the choice to optimise non-zero time periods better "reflect[s] active spending decision[s]", but when reporting Robyn's recommendations to stakeholders, an "overall budget reallocation strategy" is preferred.

**Comment by Leonelsentana** [comment]
Hi @Steven-Livingstone, 
Covering while Gufeng is off. I think you are heading into the right direction but I guess it may be better to work on total_spend instead of spend_share to apply the optmSpendUnitDelta. So that you work in absolute (not %) total spend terms, therefore, increase the absolute values by total_spend (from certain channel) * (1 + optmSpendUnitDelta), then divide by the total_spend. This is because the actual shares might be reduced in the presence of zeros and you would want that share to be fairly changed in absolute terms for total_spend before recalculating the share, if that makes sense. In Gufeng's example. If you have spend c(0, 0, 0, 5, 15), and effects (or responses) are c(0, 0, 0, 10, 20), then mean spend would be 10, mean effects would be 15, the delta would be calculated as a percentage (optmSpendUnit / initSpendUnit -1), let's say linearly in this case assuming the channel constraints allow for that, then optmSpendUnitDelta would be 0.5 and optm_spend_share would be 1.5 **BUT over a spend_share that already embeds non-zero values in the calculation.** So the suggestion would be to instead just use the absolute delta from the budget allocator in the example it is 5 (15-10) in the file (optmSpendUnit - initSpendUnit) and then add it to the total absolute spend (without dividing by total data points zero and non-zero) you have for that channel, in the example 20, so 20+5 = 25 and then divide if you want by the total spend cross-channel in the period you used within your window to calculate the share of spend. The same with the response if that makes sense, using absolute response should be the key.

**Comment by Leonelsentana** [comment]
Hi @Steven-Livingstone,
Hope you are well. Covering while Gufeng is off. You are heading into the right direction, however you may want to work on total_spend instead of spend_share to apply the optmSpendUnitDelta. So that you work in absolute (not %) total spend terms, therefore, increase the absolute values by [total_spend (from certain channel) + ((optmSpendUnit - initSpendUnit) x non-zero time_units (non-zero spend weeks or days in your window), then divide by the total_spend]. This is because the actual spend_share from total_spend may be reduced in the presence of zeros and you would want that share to be fairly changed in absolute terms for total_spend before recalculating the share. In Gufeng's example. If you have spend c(0, 0, 0, 5, 15), then mean initSpendUnit (Non-zero) would be 10, let's assume optmSpendUnit(Mean per unit of time) is 15 (optmSpendUnit - initSpendUnit would be: 15 - 10 = 5) then multiply by non-zero periods (5 x 2 = 10), finally you may have to add it to the total absolute spend for that channel, in the example 20, so 20 + 10 = 30 and then divide if you want by the total spend cross-channel in the period within your selected window to calculate the share of spend E.g. if total spend was 150 then 30/150 = 20% optimized new share of total spend.
Hope it helps :)
