### ISSUE TITLE
Combining response curves across models

### ISSUE THREAD

**Issue by RaviP1987** [facebookexperimental/Robyn#233]
Hi Gufeng, FB team

I have a brand with multiple SKUs, with different sales drivers across SKUs, except media (TV, FB etc). Given difference in drivers, I need to make 1 model for each SKU (total 4 SKUs). However, given media is same, I want to see the response curve across the brand (and not just SKUwise). 

Can you please advise if there is a way I can combine the 4 different response curves into one?. I am thinking of just summing up the Sales response across 4 SKUs and i wanted to check if the output present in 'pareto_media_transform_matrix' refers to the media impact that is used to make up 'Y axis' of response curve ? Sorry, I am not sure of this content of this file (couldnt find documentation).

Thanks very much

**Comment by gufengzhou** [comment]
in pareto_media_transform_matrix, under column "type", you can find "decompMedia" that is the response on the Y-axis and "adstockedMedia" that is the X-axis. Also a fun fact: when you do decompMedia / saturatedMedia, you will get a constant that is the coefficient of this variable;)

Actually very interesting use case. because the media drives all 4 SKUs, when modelling each SKU, the ROIs will be of course too high because the spend is for all 4 SKUs. It does sound reasonable to sum up the contribution of each SKU to get to total. It's quite interesting to think about using this sum for Y axis while using the same x-axis. Because the hill transformation is continuous/differentiable, the sum should also be continuous visually. So it probably will work. However, we don't know the parameters (alpha and gamma) of the "unified response curve", so it can't be used for budget allocation, unless we try to fit this "unified response" with hill function again...I'm not even sure if the new curve can be fitted by Hill. Anyways, hope it helps and happy analysing :)

**Comment by RaviP1987** [comment]
Thanks so much Gufeng! appreciate your time and advise!
