### ISSUE TITLE
Panel data and Python port

### ISSUE THREAD

**Issue by raz1470** [facebookexperimental/Robyn#280]
Hey.

Great work!

Apologies to raise this on issues but I don’t have a Facebook account to raise in the group.

Are you able to give an estimated date on Python port and the ability to use Panel
data?

I know they are big tasks but I need to decide whether I need to recruit an R developer or whether it’s better waiting for a port.

**Comment by gufengzhou** [comment]
Thanks! Regarding Python, due to the challenge of maintaining two languages at the same time during active dev, we'll not offer native Python version until stable version of Robyn. As intermediate solution, we're looking into putting out rpy2 wrapper in H1. 

For panel data, it'll be rather H2 this year as there're other higher priorities. 

Hope it helps.

**Comment by raz1470** [comment]
Ok thanks. Is there anywhere I can see your planned changes over the next few months?

**Comment by gufengzhou** [comment]
Hey sorry that we're not releasing the active production log because it's often hard to commit to ETAs.
