### ISSUE TITLE
Differences in calculating media decomp.RSSD in initial training and refresh

### ISSUE THREAD

**Issue by joangcc** [facebookexperimental/Robyn#290]
## Describe issue
Robyn's model.R script has two different ways of calculating decomp.RSSD for paid_media_vars.
Lines 561-568 of model.R script:
```
          if (!refresh) {
            decomp.rssd <- dt_decompSpendDist[, sqrt(sum((effect_share - spend_share)^2))]
          } else {
            dt_decompRF <- decompCollect$xDecompAgg[, .(rn, decomp_perc = xDecompPerc)][xDecompAggPrev[, .(rn, decomp_perc_prev = xDecompPerc)], on = "rn"]
            decomp.rssd.nonmedia <- dt_decompRF[!(rn %in% paid_media_vars), sqrt(mean((decomp_perc - decomp_perc_prev)^2))]
            decomp.rssd.media <- dt_decompSpendDist[, sqrt(mean((effect_share_refresh - spend_share_refresh)^2))]
            decomp.rssd <- decomp.rssd.media + decomp.rssd.nonmedia / (1 - refresh_steps / rollingWindowLength)
          }
```
See how decomp.rssd in initial training is the square root of the **sum**, while in refresh is the square root of the **mean**. Is it a bug? If it isn't, what is the reasoning behind it?

Thanks!

Joan
## Environment & Robyn version
Robyn code version: 3.5.0

**Comment by gufengzhou** [comment]
Hi, very good catch but it's actually intended. 

First of all, changing to mean or sum won't have impact on performance because sum is just mean times n, so the error to be minimised as objective function works either way. 

As you see, we calculate decomp.rssd differently for refresh. The reason is this: Assuming we have 100 days in initial model and want to refresh 7 days forward, so the refresh is built on day 8-107, with day 101-107 as net new datapoints. As you will realise, we will expect baseline vars (trend/season/context etc) to be rather stable, but for media we will expect it to be more responsive if we're making big budget change in day 101-107. We realised that we need to also control for the stability of non-paid variables while refreshing. That's why we have two components of decomp.rssd for refreshing,  `decomp.rssd.nonmedia` and `decomp.rssd.media`. 

Now I'm getting to your question about sum vs mean. Assuming again we have 3 non-paid variables that are trend, season & competitors and 10 paid media vars. When I do sum, `decomp.rssd.media` will get more weight than `decomp.rssd.nonmedia` because it just has more variables. With mean, we treat them equally. 

Well, on the other hand, you see in the last line of code that we put again a weight that's depending on %of net new datapoints, because we do want to allow larger changes for baseline when lots of new datapoints are added.

The refreshing mechanism is still very new and experimental. We would love to know your thoughts.

@igorskokan @Leonelsentana  @laresbernardo  @kyletgoldberg

**Comment by gufengzhou** [comment]
please reopen if necessary
