### ISSUE TITLE
documentation - analysts guide: nloptr vignette link broken

### ISSUE THREAD

**Issue by extrospective** [facebookexperimental/Robyn#313]
Broken link in documentation

## Describe issue

Analysts guide says:

```
Robyn's budget allocator uses the gradient-based nloptr library to solve the nonlinear saturation function (Hill) analytically. For more details please check the [vignette](https://cran.r-project.org/web/packages/nloptr/vignettes/nloptr.pdf) of the nloptr library.
```

The link to nloptr.pdf does not work.

While I did find this: https://rdrr.io/cran/nloptr/f/vignettes/nloptr.Rmd, I have no idea if that is the intended link.

**Comment by laresbernardo** [comment]
Hi @extrospective 
This was the intended documentation link: https://cran.r-project.org/web/packages/nloptr/nloptr.pdf
They must have changed it. Feel free to read more about `nloptr` in CRAN ([here](https://cran.r-project.org/web/packages/nlme/index.html)).
Thanks for reporting this. We'll get it fixed in the documentation soon.
