### ISSUE TITLE
Error in robyn_save

### ISSUE THREAD

**Issue by tgtod002** [facebookexperimental/Robyn#330]
## Describe issue
I am getting this issue in robyn_save:

Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'C:\Users	todor\OneDrive - Vericast\Documents\AFW_MMM_Model\MMM_AFW_Model_Object.RDS', probable reason 'Invalid argument'

**Comment by laresbernardo** [comment]
Hi @tgtod002 
- How can we replicate this problem?
- I [Googled](https://stackoverflow.com/questions/15363076/error-in-gzfilefile-wb-cannot-open-the-connection-or-compressed-file) this issue and it might be caused by the long file name. Please use `setwd("C:\Users todor\OneDrive - Vericast\Documents\AFW_MMM_Model")` or save it in a less deep folder.

**Comment by tgtod002** [comment]
Hi,  I did the same thing.  I moved the object to my c: drive.   to simplify the directory structure.  It worked.

**Comment by laresbernardo** [comment]
That's great. It seems like an old RStudio bug with Windows users. Thanks for letting us know that worked
