### ISSUE TITLE
Error in set_holidays

### ISSUE THREAD

**Issue by Aanai** [facebookexperimental/Robyn#368]
## Describe issue

When using weekly data, there is an error if the week start is other than Sunday or Monday. (In my case it is Friday)

> Error in set_holidays(dt_transform, dt_holidays, intervalType) : 
  Week start has to be Monday or Sunday

## Environment & Robyn version
Using the latest R version and Robyn 3.6.2

**Comment by laresbernardo** [comment]
Hi! This is actually an intended error/warning. Please, provide your weekly data to be set on Sundays or Mondays. You can simply +2 to your date values (i.e. `df$dates <- df$dates + 2`). Given the weekly trend won't be used because of your data granularity, your results shouldn't be affected either.
