### ISSUE TITLE
Variables used for modelling

### ISSUE THREAD

**Issue by giorgossideris** [facebookexperimental/Robyn#395]
## Describe issue
After having a look at the code of the project, I concluded that <code>InputCollect.all_media</code> attribute refers to the media variables (both paid and non-paid) to be used for modelling. But, [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L227) the <code>paid_media_spends</code> are used instead of the <code>paid_media_vars</code>. As a result, the modelling is performed based on the spend of the media campaigns, and not the exposure media metrics.  
This can also be seen in the waterfall plot below, where only labels about the spend on paid media campaigns can be found (the plot is extracted by the <code>demo.R</code> script).
![image](https://user-images.githubusercontent.com/56915448/170346988-328a0334-141c-4968-b6e8-e1688d1ea9be.png)

**Comment by kyletgoldberg** [comment]
yes - this is intended, check the release notes for 3.6.0 https://facebookexperimental.github.io/Robyn/docs/releases/#360

**Comment by giorgossideris** [comment]
Hello @kyletgoldberg and thank you for your response! Can I find more details about this change somewhere? As, if I understand correctly, there is no reason for providing exposure media metrics in input.

**Comment by kyletgoldberg** [comment]
Hi,

Check the conversation here - https://www.facebook.com/groups/robynmmm/posts/1174300543338077/

We still recommend including the exposure metrics in order to identify places where variables should potentially be split into smaller variables in order to better understand these channels that may have poor correlation between spend and exposure.
