### ISSUE TITLE
Media excluded in optimiser because their coeffients are 0

### ISSUE THREAD

**Issue by gibrano** [facebookexperimental/Robyn#40]
## Issue

I would like to know, how can I avoid zero coefficients in the training process?.

## Steps to Reproduce

My hyperparameters are:

![image](https://user-images.githubusercontent.com/21179249/112557890-22e3de80-8d93-11eb-922a-4a95a026ff47.png)

## Expected Behavior

I would like to have non zeros coefficients, in google search brand or other media channel.

## Actual Results

![image](https://user-images.githubusercontent.com/21179249/112557740-c1bc0b00-8d92-11eb-98ca-a90abd2a9ede.png)

## Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hey, thanks for trying out Robyn. Well we don't directly force the model to not produce 0 coef at all, because we did this before and got issues when there were really weak variables inside that "deserved 0". As you know, you get a set of Pareto output. If all results are not satisfying, I would recommend to run a higher set_trials, e.g. 80, to get more results. Maybe there will be some results that are not reducing your search to 0. Does it make sense?

**Comment by gibrano** [comment]
It's good to know it @gufengzhou, and it make sense, but there are still cases like google brand where it is necessary to protect the brand and assign a budget, in the same way thanks for the feedback.

**Comment by gufengzhou** [comment]
What you can also try is increase the range of theta for brand. You're using 0-.3 now, you can try 0.3-0.9 to see if you get better result there. If that still doesn't work, try further splitting brand into more granular variables. Hope it helps.

**Comment by Leonelsentana** [comment]
Hi @gibrano as Gufeng said, thanks so much for using our code :) 
The steps I usually take are:

1. Increase iterations/trials. If that does not work then:
2. Increase thetas and/or gammas which will increase the effect of time of the media and delay the saturation point. If that does not work then:
3. Try different train/test split ratios. You may analyze the correlation of the brand channel with the response (e.g sales) for both the train and test split periods. Ideally both periods should have a similar correlation and representation of the brand channel in question.
4. If none of the above work, try to see if different channel aggregations may help for this case?
Hope it helps and thanks for trying out Robyn!

**Comment by gufengzhou** [comment]
one more thing. I just saw that in the budget allocator, you have the upper contraints as 1.0 --> this means you don't allow any increase of spend. That's why you see unreasonable allocation results. upper constraint should be above 1

**Comment by gibrano** [comment]
Hi @gufengzhou and @Leonelsentana, thank you so much for the follow up you have given to the case. Following your advises, I have increased iterations to 800 and trials to 80, also I have splited the campaigns into more granular variables with hyperparameters:

![image](https://user-images.githubusercontent.com/21179249/113036024-052ac680-9151-11eb-97db-ea6b3aacd872.png)

My results with the Budget Allocator keeps giving me zero in some coefficients:

With max_historical_response:

![image](https://user-images.githubusercontent.com/21179249/113036394-78ccd380-9151-11eb-97dd-1b65b61a6858.png)

With max_response_expected_spend:

![image](https://user-images.githubusercontent.com/21179249/113036476-9a2dbf80-9151-11eb-947d-dc0d6379a876.png)

Something I would expect with lowers and uppers bounds is that the budgets don't go out of bounds. On the other hand, I notice that in the plot of Response curve and mean spend by channel, there are positive values or positive budgets for each of the channels, or I don't know if I am misinterpreting it. 

![image](https://user-images.githubusercontent.com/21179249/113037833-08bf4d00-9153-11eb-9bc0-f4e9838d757e.png)

I appreciate your help.

**Comment by gufengzhou** [comment]
Generally speaking, Robyn does not guarantee all coefficients to be non-zero. We use ridge regression, a shrinkage method that will also reduce coefs to 0 when the correlation between that feature and dependent variable is "too weak". So there's no guarantee that all media will be non-zero.
Having said that, also with 800 * 80 total iterations, not one of the pareto optimal models is non-zero? If this is the case, one thing you could do is to increase the amount of pareto outputs and "hope" that you can get one non-zero. As you know, I'm outputting 3 pareto fronts by default, which can be increased (although quite hidden). In the .func script line 1439, I define the number of pareto fronts as `paretoFronts <- c(1,2,3)`. You can try to increase to 1-5 or even higher, so that you can get more results. Of course the trade-off is clear: the higher the front number, the worse the model performance in terms of NRMSE and DECOMP.RSSE. But with 800*80 iterations, I can imagine higher fronts might still be quite good. Please try this and let me know if it works. 
Regarding the positive budget in response curve plot, well for those 0 coef channels, you will still have a mean spend, but the responses are zero. You can also see that these channels response curves are just an horizontal line.

**Comment by gufengzhou** [comment]
Another thing worth trying is what Leo mentioned as second point: increase the bounds of hyperparameters for the 0 coef channels, esp. theta to 0 - 0.9 and gamma to 0.1 - 1. I see that you changed the thetas to 0.5-1. By increasing the bounds, we don't mean make it higher, but rather give the model more freedom. For gamma, usually we don't recommend to set it too low (allowing inflexion point to happen early). But in your case it might be worth trying. Let us know how it works.

**Comment by gufengzhou** [comment]
Feel free to reopen this if more issues occur
