### ISSUE TITLE
Convergence question

### ISSUE THREAD

**Issue by Da5413lions** [facebookexperimental/Robyn#403]
Hi team,

Thank you for all your work. I managed to successfully run Robyn. But I need help understanding this result from the pareto plot.

![Rplot](https://user-images.githubusercontent.com/106715239/171526416-1024ed4a-8b5d-42f6-a403-b0652f628dd7.png)

DECOMP.RSSD NOT converged: sd@qt.20 0.11 > 0.064 & med@qt.201 0.25 > 0.22
NRMSE converged: sd@qt.20 0.00031 <= 0.022 & med@qt.20| 0.093 <= 0.14

I assume we're dealing with standard deviations (sd) and confidence intervals (qt) here. Can you elaborate on how these numbers are interpreted? I would appreciate any external sources that provide an explanation. Thank you.

**Comment by Leonelsentana** [comment]
Hi @Da5413lions, 

In Robyn, we consider the model to be converged when:

Criteria #1: Last quantile's standard deviation < first 3 quantiles' mean standard deviation

Criteria #2: Last quantile's absolute median < absolute first quantile's absolute median - 2 * first 3 quantiles' mean standard deviation

The quantiles are ordered by the iterations of the model, so if we ran 1000 iterations, the first 200 iterations would make up the first quantile. These two criteria represent an effort to demonstrate that both the standard deviation and the mean for both NRMSE and DECOMP.RSSD have improved relative to where they began, and they are not as variable. Both mentioned criteria have to be satisfied to consider MOO convergence.

This is under revision as we believe that the main score that should be considered for convergence is NRMSE (Model error, which in your case actually converged), this is because not necessarily the fact that DECOMP.RSSD is converging to small values means that the model quality is better, it is just providing less radical recommendations in terms of differences on the share of spend and share of effect. E.g. if you have 50/50 investment in channel A and B respectively, then a model that tels you the effect is 100% for channel A would be of very high DECOMP.RSSD, where a model closer to that 50%/50% in terms of effect would have very low DECOMP.RSSD.

Hope it helps :)

**Comment by Da5413lions** [comment]
Thank you @Leonelsentana . Very helpful.

In criterion 2, I suppose you meant: Last quantile's absolute median < absolute first quantile's absolute median - **3** * first 3 quantiles' mean standard deviation

Is there a particular reasoning for this choice?

**Comment by Leonelsentana** [comment]
Hi @Da5413lions, glad it helped,

Please check that is Last quantile's absolute median < absolute first quantile's absolute median **- 2** * first 3 quantiles' mean standard deviation now, we changed that, it used to be 3 before to make the rule a bit less strict, please have in mind this is just an indication proxy for convergence and the model will always run the same way no matter what the convergence scores give as a result. The reasoning behind is that if the last quantile median is 2 SDs away or more from the first quantile's median as a result of the optimization process, it should be converging to a significantly lower median value for the score.
