### ISSUE TITLE
test on different data and context vars transformation

### ISSUE THREAD

**Issue by desilollo** [facebookexperimental/Robyn#416]
Hi,
I've built an MMM model with Robyn and saved one of the best model. Now I'd like to use the same model previously saved on a slightly different dataset (same date range) and get the one-page plots output as well as the csv files. How I could do it?
Furthermore, when transforming the context vars, should it be transformed prior to the glm regression or while performing the regression?
Thanks in advance.

**Comment by Leonelsentana** [comment]
Hi, would you clarify what you mean by a "slightly different data set for the same date range?" What would be the rationale of using a model trained on certain data and use it in the same date range again with almost the same data? The refresh function is useful for example for re-running selected models on top of new data, however I dont quite understand why would you do what you suggested if I understood correctly. Moreover, what do you mean about transforming context vars? We input context vars with a pre-transformation which makes them continuous via prophet but do not do much more

**Comment by desilollo** [comment]
Thanks for the clarification, do you have any resources or papers where I can find some more information about the pre-transformation of variables such as distribution, promotion and price?

**Comment by Leonelsentana** [comment]
Hi, please refer to the code directly, we do not transform context_vars via prophet unless they are factors, so that we can convert them into numeric:
https://github.com/facebookexperimental/Robyn/blob/9358e455fd79a7e60219b131dbab05f42b0f0721/R/R/inputs.R#L703
For the rest, we just use them as inputs directly into the code. What would be your use case here? I am struggling to understand what would you use this for based on your original comments.

Thanks!
