### ISSUE TITLE
I can't install robyn_inputs package

### ISSUE THREAD

**Issue by Sibusiso1995** [facebookexperimental/Robyn#421]
I'm in need of assistance with installing robyn_inputs packages. I tried updating my R and I still got the same version of R even if I downgrade.

The R version I'm using is 4.2.0
The Robyn version I'm using is 3.6.4

<img width="609" alt="Screenshot 2022-06-30 at 10 55 17" src="https://user-images.githubusercontent.com/54172627/176636146-55ae27f0-ee2c-467b-a579-aebcb0f7a02d.png">

**Comment by laresbernardo** [comment]
Hi @Sibusiso1995 
`robyn_inputs()` is a function of the `Robyn` package. You just have to install `Robyn` to be able to use all its functions. Please, follow the steps in the [demo](https://github.com/facebookexperimental/Robyn/blob/main/demo/demo.R) or the q[uick start](https://facebookexperimental.github.io/Robyn/docs/quick-start/) guide. I also strongly recommend learning the al least the basics of R before you continue.

**Comment by Sibusiso1995** [comment]
Is there any way I can get the link to check out the basics? Cause I have watched the quick start guide before and used the demo so I wanna try a different approach. The warning message is there any way I could solve it

**Comment by kyletgoldberg** [comment]
@Sibusiso1995 The best approach to getting to know the package after familiarizing yourself with the demo is typically going through the demo but substituting in your own data. This will help you understand better the ins and outs since you are most familiar with your own data. Aside from that, the website is going to be the best resource to explain technical concepts, etc. Hope this helps
