### ISSUE TITLE
Regularization parameter & intercept

### ISSUE THREAD

**Issue by Cyrinehl** [facebookexperimental/Robyn#436]
## Describe issue
Hello,
I have multiples questions about Robyn: 
1- The first one concerns the regularization parameter. Is it possible to manually set the hyperparameter ? from my understanding, the lambda_control is no longer usable. Is that correct ? If so, is there another hyperparameter that we can use to control the regularization ourselves?

2-The second question is about the intercept. Generally speaking, how can we make it bigger ? I have multiple explanatory variables and I do apply either the weibull transformation or the geometric transformation. I thought about saturating even more the transformations but it didn't increase much more the intercept. Is there another way/trick that could help me? 

## Environment & Robyn version
R version (R --version)
We do use the latest Robyn version !

Thanks a lot for helping !

**Comment by laresbernardo** [comment]
Hi @Cyrinehl 

1. That's correct, we don't have `lambda_control` parameter enabled since v3.6.0, given it's a hyperparameter. This decision was made to minimize bias in lambda selection by picking the values that minimize the 2-3 errors we are optimizing towards. You could fix a values by setting them as values instead of ranges using the `dt_hyper_fixed` parameter. On the other hand, there is an experimental parameter, `add_penalty_factor` which is not enabled by default and can give you more control over the regularization. Check glmnet's `penalty.factor` for more information.

2. Why do you want a larger intercept exactly? Higher baseline based on your knowledge? The first thing that comes to my mind is picking (out of the best models) the model that has a larger intercept chunk based on the decomposition plot. Also, we encourage you to provide calibration data based on experiments to activate the MAPE as a third optimization objective; this is the best way to get as close as possible to ground truth.
