### ISSUE TITLE
Very large and always positive residuals

### ISSUE THREAD

**Issue by DzimitryM** [facebookexperimental/Robyn#462]
## Describe issue
In some of the output solutions the difference between actual and predicted response is large and always positive.
This issue takes place after upgrading Robyn from v3.6.3 to v3.7.0 / v.3.7.1.
An example of a strange output, it was chosen by the internal clustering algorithm as one of the best.
![1_149_6](https://user-images.githubusercontent.com/8161754/183926564-1d1c3aa5-eeb0-4420-ad2a-133d4b64f5b2.png)

## Provide dummy data & model configuration
Running the original `demo.R` without modifications gives such kind of outputs.
It uses weekly simulated data.

Working with 'the real world' data also provides such biased predictions even more often.

## Environment & Robyn version
R version 4.2.1
Robyn version: 3.7.0, 3.7.1

**Comment by laresbernardo** [comment]
Yes! Good catch @DzimitryM 
Missed adding the intercept to depVarHat. Already pushed a [fix](https://github.com/facebookexperimental/Robyn/commit/256dd6f8283175c458180c18da307c8ea4316471). Please, feel free to update the package and re-try and close if the issue is solved. Thanks for noticing and reporting!

**Comment by DzimitryM** [comment]
Thank you @laresbernardo for the prompt fix
