### ISSUE TITLE
Question about budget allocation

### ISSUE THREAD

**Issue by satomi999** [facebookexperimental/Robyn#479]
Hello, thank you for creating Robyn!
I have tried to run robyn_allocator, but I am not sure how to interpret the following two points.
Sorry to bother you, but could you please give me your thoughts on the questions below?

### 1. Initial average response by robyn_allocator and original average response
Why does the initial response before optimization computed by robyn_allocator not match the original response output in pareto_alldecomp_matrix.csv?

The initial response by robin_allocator is 28 (red circled area in the image below).
<img width="657" alt="1_228_4_reallocated_respo1" src="https://user-images.githubusercontent.com/98081674/187610578-f07a4695-8d85-4382-a3d0-116aa2860b6d.png">

However, the original response output to pareto_alldecomp_matrix.csv is 149. (Average of responses within the period of date_min and date_max specified by robyn_allocator)
<img width="326" alt="pareto_alldecomp_matrix" src="https://user-images.githubusercontent.com/98081674/187611666-69c1522c-2b00-4b0d-875e-6db7af892618.png">

28 and 149 are quite far apart and I am confused as to why this is happening.

### 2. Relationship between CPA, response curve and optimized budget allocation
robyn_run results showed that one ad had a low CPA and the response curve was not saturated (red circled area in the image below indicates that ad).
<img width="850" alt="1_228_4" src="https://user-images.githubusercontent.com/98081674/187611893-6b34bfbb-aeb3-4cc6-8f49-bab6ed9bdb9b.png">

I'm wondering if we could increase the budget for that ad and get a better response.
However, we question that the values after optimization by robyn_allocator are low budget (and low response). (red circled area in the image below).
<img width="657" alt="1_228_4_reallocated_respo2" src="https://user-images.githubusercontent.com/98081674/187611949-bd0d991f-a89a-4924-8a9f-1a4fc2c11df3.png">

I'm wondering if the optimized budget allocation takes into account the CPA and response curve of the ads. 
How should these results be interpreted?

Thanks.

## Environment & Robyn version
Robyn version 3.7.1

**Comment by gufengzhou** [comment]
to 1), there's some nuanced difference between mean response from allocator and your averaged response from pareto_alldecomp_matrix.csv. Mean response is the response of mean spend, basically putting the mean spend on the response curve and get that response point, instead of just averaging response of all weeks. Another nuance is that in allocator we don't apply adstock, while in the modelling output we do. The reason is that adstock is sequential and needs a date, while when doing allocation, we don't really have a date for the spend that user is inputting. So we decided to use raw instead of adstocked spend in allocator to give a "conservative estimation" of the response. We'll address this difference though in the future with the new forecast function, where we can apply adstock, trend/season and different scenarios.

2) if i can recognise the graph correctly, the circled gree should be the steep increasing curve on the left? if yes, it means in deed that this channel should have potential to get more budget. you can try increasing the upper constraint for this channel in the allocator and try again. you should be able to see more budget allocated to it

**Comment by satomi999** [comment]
@gufengzhou 
Thank you for your response !

1. OK, I found that the average response is calculated differently.

>  Another nuance is that in allocator we don't apply adstock,

But in robyn_response called from robyn_allocator, there is a code to do adstock, but is this process not applied?
https://github.com/facebookexperimental/Robyn/blob/b558cdedb26355feaa28e92c3cb27e396b6c93a4/R/R/response.R#L226

2. I changed the upper constraint for this channel in the allocator, which increased budget allocation and response.
Thank you!

**Comment by gufengzhou** [comment]
good one. the adstocking part in the response function is to recreate the saturation curve: because all saturation curves are created during the modelling process, so it requries adstocking. But the `metric_value` isn't affected by this part, due to the reason I explained before. I'm aware that this approach is not intuitive for many users and is a intermediate solution until we update it in the forecast function.

**Comment by satomi999** [comment]
@gufengzhou 
I see, it's the adstock process for recreate the response curve.
Thank you for your time.
