### ISSUE TITLE
Channels missing in budget allocator

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#489]
The budget allocator is missing some channels, is there a way to stop from making those 0?
And there are some channels that are mostly used for awareness so their response conversions are very less but these are required. How to make sure these channels are not 0 in the budget allocator

**Comment by gufengzhou** [comment]
You should start with selecting a proper model, instead of jumping over to allocator. Please share your model onepager To start with

**Comment by virithavanama** [comment]
![3_159_7](https://user-images.githubusercontent.com/89505409/189661055-6661313c-4d32-4adf-90cb-44e2712506bc.png)
This is the best model we picked out of all the models.

**Comment by gufengzhou** [comment]
In general, regression is correlational. If your independent vars are weakly correlated with dependent, there's no model in the world that can prove otherwise. 

There're some tuning opportunities though. First I'd start with reassessing your set of predictors. Is it possible that some important business drivers are missing? What's the adjusted R squared of your selected model? Please check the comment from Igor here about how to "map" your business for MMM https://m.alpha.facebook.com/groups/robynmmm/permalink/1268695020565295/

Otherwise, try out weibull_pdf adstock to enforce lagging effect and benefit from lagged correlation. Also try out penalty factors in robyn_run as additional hyperparameters to allow more degree of freedom for the evolutionary algorithm and find potentially better fit.

**Comment by virithavanama** [comment]
is there a way where we can strictly make sure the channel is not dropped at all?

**Comment by gufengzhou** [comment]
Short answer is no. If your data is a flat line, it'll be no effect. MMM is no magic. on the above I mentioned couple of "tuners" to build a better model

**Comment by virithavanama** [comment]
There are some channels that are mostly used for awareness purposes(impressions) not for conversions. So if there are very less conversions the effect share is almost 0 but we need these channels and also need to estimate the budget for these. Any suggestions to handle this situation?

**Comment by Tomobay** [comment]
@virithavanama 
> There are some channels that are mostly used for awareness purposes(impressions) not for conversions
But ultimate goal is to get conversions? If my understanding is correct does channels are not getting conversions in short term but getting conversions in long term. 
If that's the case you should try Weibull PDF for adstock.
- For short term channels shape can be c(0.0001, 10). 
- For long term channels shape can be c(2.0001, 10)

For more detail https://facebookexperimental.github.io/Robyn/docs/analysts-guide-to-MMM

**Comment by virithavanama** [comment]
We don't expect awareness channels to directly create conversions, we expect it to impact conversions on other channels

**Comment by gufengzhou** [comment]
You're talking about many different things. If you expect channels interact with each other, it's usually solved by multiplicative model, which Robyn doesn't offer yet. If you expect some long-term and/or indirect effect, you could try it out using survey based brand equity as intermediate metrics in a two-step model (spend->brand->sales) in Robyn. However, none of these will guarantee the effect. 

As suggested my me and others above, definitely try out different hyperparameter ranges and penalty.factor for finetuning.

**Comment by gufengzhou** [comment]
Please reopen if this issue reoccurs.
