### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by muuratjann** [facebookexperimental/Robyn#491]
Dear team,

Thank you a lot for your replies and a great work. I have several questions:

1. I have a data on TV spendings:
   Last week the cost was 1000$ with 40% discount it becomes 600$
   This week the cost was 1000$ with 60% discount it becomes 400$
How should I feed this into the model? If I include the original cost without discount, it seems like it does not reflect the real spendings. If I include the discounted cost, the effect of same spending this week and last week would not be the same.

2. Is there a way to make the hidden CPA be seen in the plot? 
<img width="589" alt="Screenshot 2022-09-14 at 11 55 35" src="https://user-images.githubusercontent.com/49808871/190123389-01fc641a-7bf3-4b68-af17-0bab39a378fc.png">

3. My variable to data ratio is 1:7 but it does converge with high R2 and results seem to be stable across different clusters. So, is the recommendation of 1:10 a must or nice to have? 

4. I have event data in my context_var which I include in factor_vars. I have seen here: https://github.com/facebookexperimental/Robyn/issues/416#issuecomment-1165390169 that when I make it a factor, then it should get transformed. But in the plot I do not see it being transformed, it seems like the effect is added to the corresponding week only.
What might be the problem?
<img width="708" alt="Screenshot 2022-09-14 at 12 04 44" src="https://user-images.githubusercontent.com/49808871/190125480-455956b8-5049-4627-9261-c5b5f1d75b0e.png">

Thank you in advance.

**Comment by gufengzhou** [comment]
Thanks for reaching out. 

1) it's a very interesting case. The most important thing is that your predictor should reflect the media pressure over time. If it dropped last week just because of discount, while your ad was the same as before, you shouldn't adjust it. You could manually adjust it though afterwards. Maybe it's worth thinking about providing an feature to account for media spend discounts 
2) we'll check. Until then you can also just recreate plots using the csv outputs. 
3) it's just nice to have/ being conservative. 1:7 should be fine
4) factors being transformed means it gets converted into a continuous variable. But Robyn doesn't apply adstock or saturation on context_vars.
