### ISSUE TITLE
Error message: could not find the function robyn_write 

### ISSUE THREAD

**Issue by marta-riva** [facebookexperimental/Robyn#497]
## Describe issue
I am running the demo code without modifying anything. 
Everything is correct until I get to the point:
`ExportedModel <- robyn_write(InputCollect, OutputCollect, select_model)`
There I receive an error message:

```
Error in robyn_write(InputCollect, OutputCollect, select_model) : 
  could not find function "robyn_write"
```
I hope I provided all the information. I tried to update and re-load the library but it does not work anyway
## Provide reproducible example
After get the OutputCollect list I printed it and choose one of the values included in this set it as chosen model

## Environment & Robyn version

- Robyn version: `packageVersion("Robyn")` --> ‘3.7.3’
- R version --> 4.2.0 (2022-04-22)

**Comment by laresbernardo** [comment]
Hi @marta-riva 
Can you please run `?Robyn::robyn_write()` and see if you can access the documentation? 
This error usually happens when a) the library hasn't been loaded in your session yet or b) you have an older version that still doesn't have that new function [which is not the case - 3.7.3 is OK].

**Comment by marta-riva** [comment]
I actually had an "Internal Error". Quite weird because I loaded the library many  times before asking (also checking for the updates). I quit and re-start the session and now it works. 
Thank you very much for the fast answer.
Have a nice day
