### ISSUE TITLE
channels with long time gaps

### ISSUE THREAD

**Issue by virithavanama** [facebookexperimental/Robyn#500]
how to handle the scenario when there are different channels but the campaigns for those channels are not run continuously except for 1 and so there are so many 0s.

**Comment by gufengzhou** [comment]
many 0s mean little variation in this variable, which is bad for any models. When you're not spending much on one channel, you also can't expect much response. I'd recommend to meaningfully combine sparse variables

**Comment by michaelwexler** [comment]
Hmm... that's correct from a modeling pov, but doesn't reflect the reality of marketing.  There can be annual sponsorships or other event based marketing; there can be publisher constraints preventing spend, etc.  

@gufengzhou, it sounds like you are assuming that sporadic spend means low spend.  That's not true in all cases; I may spend a gazillion dollars on a single-event sponsorship once every year, which is 40% of my budget, but that's just for one event.  It's high spend, but it's infrequent.   This creates a pattern with lots of 0 spend in many periods, and a big spend in one.   For some, it's a large football game, for others, it's a trade show, but you get the idea.

Will Robyn's approaches handle that situation?   It's somewhat common in large companies esp. those with strong offline spend, and less common for smaller operations esp. ones with mostly digital "always on" campaigns.

**Comment by gufengzhou** [comment]
Yes you're right about events like superbowls etc, which is the reality. Still this presents a challenge for MMM, because of only 1 datapoint. 

First of all, the adstocking transformation will spread out the value a bit, so definitely try the data as is and see if it works. If the decomp is not satisfying / too low, you might want to be creative, for example use other proxy metrics to approximate the more realistic reach of the event, maybe things like search volume or maybe social listening of your superbowl campaign, then somehow "extrapolate" the one-off spend with the proxy metric as input spend. It's about having a variable that better reflects the exposure of your one-off campaign.
