### ISSUE TITLE
Abnormal github maintenance format for the R package

### ISSUE THREAD

**Issue by avraam-inside** [facebookexperimental/Robyn#501]
Hi!  

I need to install Robyn version 3.0.0.  

There are 2 problems: 
1) Version `3.0.0` does not swing from the tap via `renv::install('Robyn@3.0.0')` 
2) I don't have direct access to github, but there is a package manager from R Studio that does. But, unfortunately, package manager does not eat this non-standard facebookexperimental/Robyn/R path, everyone always behaves normally on github, for example via facebookexperimental/Robyn.  

![image](https://user-images.githubusercontent.com/52919010/192163258-0fd1eeb2-ea57-4bef-bfab-e21784de583e.png)

The question is - how do I push this repository into package manager RStudio or when version `3.0.0` appears on "CRAN"?

**Comment by laresbernardo** [comment]
Hi @avraam-inside 
- I'd strongly recommend you use the latest version of Robyn, given we are constantly adding new features and fixing bugs.
- As you can see [here](https://cran.r-project.org/src/contrib/Archive/Robyn/), the first CRAN version is 3.6.3, and the latest (and second) CRAN version is 3.7.2. That's why you can't install CRAN's 3.0.0.
- We started documenting the [releases](https://github.com/facebookexperimental/Robyn/releases) with version 3.4.4 so using the tag '3.0.0' won't work.
- All that said, to install any previous version you can use the following code: `remotes::install_github("facebookexperimental/Robyn/R", ref = "any_reference")` where `any_reference` can be a commit ID, a branch, or a release tag.
