### ISSUE TITLE
Clarification on total ROI vs Response Curves

### ISSUE THREAD

**Issue by matteocaserio** [facebookexperimental/Robyn#578]
## Describe issue
Hello Robyn team, I have been searching the issue page for answers and I had maybe a few hints but not a clear answer.
It seems to me that when analyzing onepagers, the `Share of Spend VS Share of Effect` and `Response Curves and Mean Spends` plots are telling different stories.

See the example below:
![Selection_013](https://user-images.githubusercontent.com/106378820/208666460-24afb60a-f080-4c71-aba3-97b9035f9d37.png)

The total historical ROI for all channels is around 5. That would mean, if I understand correctly, that the model estimates that on average I have gotten $5 worth of effect for every $1 spent in the past.

So when looking at the response curves on the right, how could it be that the point of mean spend for the blue curve, for instance, corresponds to a response lower than the spend? Same for the purple curve, which seems to indicate that response for the channel is close to zero.
What the saturation curves seem to tell is that in order to actually get any positive return I should spend much more (almost a different order of magnitude) than what was done historically. How does that relate to the total estimated historical ROI of about 5?

Since the response of those curves is indeed the one used in the `robyn_allocator` output, such a model (and therefore its allocation suggestions) would not make much sense for the business.

## Provide reproducible example
Unfortunately I cannot provide our customer's data; the dataset is made of about ~700 daily observations, with 3 paid media channels (with spends and impressions), an organic variable (newsletters) and several context variables (related to promotions/discounts), along with Prophet automated seasonality, trend and holiday. The target variable is total sales on their e-commerce site.

I have experimented with many different configurations of variables, data windows, adstock types etc. but the result is always roughly similar.

Also, it might not be a data-related issue but just a misunderstanding on my part on how to read these outputs.

## Environment & Robyn version
Robyn 3.7.2 on R 4.2.2

**Comment by gufengzhou** [comment]
Hi, this question has been raised more frequently lately, for example[ this one](https://www.facebook.com/groups/robynmmm/posts/1344423226325807). Any chance you're using the weibull adstock? 

This discrepancy is due to the fact that the `robyn_response` and `robyn_allocator` functions don't conduct adstock transformation so far, while the saturation curve itself is generated with adstock. The reason is that when you input a value, say 100$, into the two functions, this value doesn't have a timestamp and without timestamp it's not possible to do adstock transformation. It's been working fine so far, as most users were using geometric adstock that is "stocking up" less, and thus the discrepancy was moderate. In comparison, weibull adstock is more advanced and becoming more popular now, and it will "stock up" more on the raw spends. Until now, we've been explaining this phenomenon as a "conservative recommendation", which means the allocator is simulating the case where adstock is 0. We've been also stressing that the allocator shows a directional recommendation, as opposed to the absolute "truth". We still see it that way, but understand that the difference is becoming too large to be ignored and the reco is coming through as unrealistic. 

This issue will be solved with the upcoming forecast function, where we'll always require a timestamp as input (or assume a timestamp by default) and thus enabling the adstocking for `robyn_response` and `robyn_allocator`. 

Robyn is still in the experimental phase and we appreciate your understanding. 

@igorskokan  @laresbernardo @michellegrushkometa @Amyhaoming

**Comment by matteocaserio** [comment]
Thank you! Makes sense. I didn't know that these two functions don't apply adstock. Is that written anywhere in the documentation? Maybe I just missed that part - it seems an important caveat. 
Will try a new training run with geometric adstock to see if the issue disappears.

Looking forward to the upcoming forecast function! Apart from this issue, it is definitely an important feature. For instance, our customer would like to see the response for future periods with certain structure of context/organic variables, and for now you could only approximate by running the allocator on past periods that where somewhat similar.

**Comment by rayliang90** [comment]
Hi @gufengzhou - have a similar, but slightly different question/concern. In the screenshots, Channel X shows 644 CPA, but the response curve for this channel is flat (in red) and so while channel X seems like a decent channel based on the CPA, it appears terrible from the response curve. 

Are we saying that the CPA (eg, the 644) does take into effect the adstock transformation, while the response curve does not, and so the Effect vs Spend Share Chart on the left is a more accurate depiction of the channel performance? 

This discrepancy seems to have implications on further analyses like simulating marginal intakes or marginal CPA as the CPA for channel X grows to a very high number based on the `robyn_response` function.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/48097288/212482494-130cd70d-c6d9-4ba1-969d-97ca20786dd8.png">

**Comment by gufengzhou** [comment]
We've just updated to v3.10 that is a big update of robyn_allocator and robyn_response. Please check the new version first.

**Comment by dohieu2801** [comment]
I have the same concern when channel X has highest ROI but the response curve look really bad.
<img width="405" alt="MicrosoftTeams-image (24)" src="https://github.com/facebookexperimental/Robyn/assets/49347619/b39d192d-bcee-4cbb-85a6-9acbe246f8b6">
![image](https://github.com/facebookexperimental/Robyn/assets/49347619/480157c8-80de-4eb4-92c1-478d078fb70d)
I understand the concept when the response curve take adstock into consideration while allocator do not. But in term of business perspective, I can't get the link of number concept and business story. Can anyone give an explanation for it? Many thanks. I used Robyn version 3.10.4, geometric adstock

**Comment by gufengzhou** [comment]
this doesn't look right @dohieu2801 , are you sure you didnt mix up the channels?

**Comment by dohieu2801** [comment]
> this doesn't look right @dohieu2801 , are you sure you didnt mix up the channels?

I'm sure that the column and the line match. All of channel above relate to digital media + commercial investment in ecomerce platform. I think I chose incorrect adstock rate (0.5-0.7 where 0.3 is recommended). Is it the reason why the result is so weird?

@gufengzhou thanks for your reply but can you also advice how can I choose the appropriate model because each time I run i get different result and the result between each iteration also very different. And the difference in model accuracy is not significant between models?
