### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#60]
# Question:

Could you please why the variables include spending and non-spending in the model together? I can understand if you put all the spending variables or non-spending variables in the model but cannot understand use both of them.   Can you please explain for me. Thanks

**Comment by Leonelsentana** [comment]
Hi @wenyanyy hope you are doing well and thanks for using our code! For the ridge regression in the model we only use whatever you define on the "set_mediaVarName" object. The spend is however always required because, in the case you would choose impressions (facebook_I) or clicks(search_clicks_P) like in the example for facebook and search respectively below, we will translate later those impressions or clicks decomposition effects from the ridge regression, into actual spend ($) values for comparability between the saturation(hill) curves for all channels in the budget allocator.
```
set_mediaVarName <- c("tv_S"    ,"ooh_S",   "print_S"   ,**"facebook_I"**   ,**"search_clicks_P"**)

set_mediaSpendName <- c("tv_S"  ,"ooh_S",   "print_S"   ,**"facebook_S"**   ,**"search_S"**)
```

Saturation curves example:
![image](https://user-images.githubusercontent.com/70534991/114695668-288e6d80-9d1c-11eb-8381-0ae976e0e948.png)

Hope it helps and happy analyzing :)
Leo

**Comment by wenyanyy** [comment]
@Leonelsentana Thank you so much for your explanation. is it possible I set "set_mediaVarName <- c("tv_S" ,"ooh_S", "print_S" ,"facebook_S" ,"search_clicks_S") instead of set_mediaVarName <- c("tv_S" ,"ooh_S", "print_S" ,"facebook_I" ,"search_clicks_P")?What's the difference between them for the modeling result?

**Comment by Leonelsentana** [comment]
Hey! Yes it is completely possible to use spend in all channels. However, we encourage analysts to try to use impressions or clicks, or any other metric for the channel (GRPs, reach, etc.) that better correlate with the actual media exposure and do not embed pricing on it. If you only put spend the model will only use spend on it and the results will be based on spend, again remember it is always better to have KPIs that reflect in a more accurate manner the media exposure (Impressions, clicks, GRPs, etc.) Hope it helps :)

**Comment by wenyanyy** [comment]
Thank you so much for it. Really appreciate~~
