### ISSUE TITLE
When will the python version be launched?

### ISSUE THREAD

**Issue by nihuizhidao** [facebookexperimental/Robyn#615]
Just wonder when will the python wrapper be ready to publish, after all python would be more friendly for many ML users, thanks!

**Comment by laresbernardo** [comment]
Hi @nihuizhidao 

We've tried enabling Robyn through a [r2py](https://rpy2.github.io/) wrapper so Python users can start using our solution, but we (and afaik anyone) haven't been able to. The main reason it's been complex comes from using [reticulate](https://rstudio.github.io/reticulate/) to call [nevergrad](https://facebookresearch.github.io/nevergrad/) multi-objective optimization function, and we can't seem to find a way around this Py > R > Py call. Also, parallel computing has been a challenge.

That said, given we are still in **development mode** and still are working on [new challenging features](https://www.facebook.com/groups/robynmmm/posts/1332065880894875/), we won't start translating a parallel version just yet because we don't have enough resources to maintain both. So, for the time being, don't expect a Python-only version in the short-mid term.

**Comment by Sandy4321** [comment]
can you do it asap pls

**Comment by ProxyCausal** [comment]
wondering why you went with R glmnet /  python nevergrad, not libraries in same language
