### ISSUE TITLE
Robyn does not recover the parameters values of siMMMulator

### ISSUE THREAD

**Issue by dmacoritto** [facebookexperimental/Robyn#625]
## Describe issue

Hello dear Robyn team,

I recently found out about the siMMMulator GitHub project. I decided to try it and run a Robyn MMM model on it to see if it managed to recover the true parameter values. I ran into several issues I could not explain, which are the following:

- When running ` InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)`, I get a warning that my exposure variable is not well correlated to my spend. Nonetheless, when running `InputCollect$modNLS$plots`, I see that all my R2 are above 0.94, so I do not understand why this warning is displayed.
- When launching the model `robyn_run`, I get this warning many times `Attention for loop i: manual decomp is not matching linear model prediction. Deviation is X%`. I have tried to figure out where does this come from, but I did not manage to find out.
- Finally, and this is the most important point, none of the output models give results close to the ground truth (I know which channel has which weight as I set them up with the siMMMulator). I made sure the hyperparameters ranges include the true parameter value but my output models are pretty far off. So I would like to ask you if you have any advice on how to tune the MMM to be able to recover the true parameters.

Below is a fully reproducible example. Thanks for your help

## Provide reproducible example

```
library(Robyn)
library(siMMMulator)
library(tidyverse)
```

### Create the data

```
#Create the dataset

#Step 0

my_variables <- step_0_define_basic_parameters(years = 5,
                                               channels_impressions = c("Facebook", "TV"),
                                               channels_clicks = c("Google_Search"),
                                               frequency_of_campaigns = 1,
                                               true_cvr = c(0.01, 0.022, 0.05),
                                               revenue_per_conv = 1)



#Step 1 - Generate baseline


df_baseline <- step_1_create_baseline(
  my_variables = my_variables,
  base_p = 50000,
  trend_p = 0.5,
  temp_var = 8,
  temp_coef_mean = 1000,
  temp_coef_sd = 5000,
  error_std = 100000)


optional_step_1.5_plot_baseline_sales(df_baseline = df_baseline)

#Step 2 - Generate costs

df_ads_step2 <- step_2_ads_spend(
  my_variables = my_variables,
  campaign_spend_mean = 329000,
  campaign_spend_std = 100000,
  max_min_proportion_on_each_channel <- c(0.3, 0.35,
                                          0.2, 0.25))

optional_step_2.5_plot_ad_spend(df_ads_step2 = df_ads_step2)

#Step 3 - Generate clicks and impressions

df_ads_step3 <- step_3_generate_media(
  my_variables = my_variables,
  df_ads_step2 = df_ads_step2,
  true_cpm = c(2, 20, NA),
  true_cpc = c(NA, NA, 0.15),
  mean_noisy_cpm_cpc = c(1.5, 5, 0.1),
  std_noisy_cpm_cpc = c(0.5, 2, 0.05)
)

#Step 5 - Adding noise to conversion rates

df_ads_step4 <- step_4_generate_cvr(
  my_variables = my_variables,
  df_ads_step3 = df_ads_step3,
  mean_noisy_cvr = c(0.005, 0.005, 0.002),
  std_noisy_cvr = c(0.002, 0.002, 0.001)
)

df_ads_step5a_before_mmm <- step_5a_pivot_to_mmm_format(my_variables = my_variables,
                                                        df_ads_step4 = df_ads_step4)

#Step 5 - Adding decay effect

df_ads_step5b <- step_5b_decay(
  my_variables = my_variables,
  df_ads_step5a_before_mmm = df_ads_step5a_before_mmm,
  true_lambda_decay = c(0.2, 0.25, 0.1)
)


#Step 5 - Adding diminishing returns

df_ads_step5c <- step_5c_diminishing_returns(
  my_variables = my_variables,
  df_ads_step5b = df_ads_step5b,
  alpha_saturation = c(2, 2, 2),
  gamma_saturation = c(0.2, 0.25, 0.2)
)

#Step 6 - Calculating conversion

df_ads_step6 <- step_6_calculating_conversions(
  my_variables = my_variables,
  df_ads_step5c = df_ads_step5c
)

#Step 7 - A few more calculus

df_ads_step7 <- step_7_expanded_df(
  my_variables = my_variables,
  df_ads_step6 = df_ads_step6,
  df_baseline = df_baseline
)

#Step 8 - Get the ROI

step_8_calculate_roi(
  my_variables = my_variables,
  df_ads_step7 = df_ads_step7
)

#Final dataframe

df_final <- step_9_final_df(
  my_variables = my_variables,
  df_ads_step7 = df_ads_step7
)



optional_step_9.5_plot_final_df(df_final = df_final)

```
### Run the `model`

```

InputCollect <- robyn_inputs(
  dt_input = df_final,
  date_var = "DATE", # date format must be "2020-01-01"
  dep_var = "total_revenue", # there should be only one dependent variable
  dep_var_type = "revenue", # "revenue" (ROI) or "conversion" (CPA)
  prophet_vars = c("trend", "season", "weekday"), # "trend","season", "weekday" & "holiday"
  prophet_country = "CH", # input one country. dt_prophet_holidays includes 59 countries by default
  paid_media_spends = colnames(df_final)[colnames(df_final)%>%str_detect(., "spend")], # mandatory input
  paid_media_vars = c("impressions_Facebook", "impressions_TV", "clicks_Google_Search"), # mandatory.
  window_start = max(df_final$DATE) - months(12),
  window_end = max(df_final$DATE),
  adstock = "geometric" # geometric, weibull_cdf or weibull_pdf
)

hyper_names(adstock = InputCollect$adstock, all_media = InputCollect$all_media)


hyperparameters <- list(
  spend_Facebook_alphas = c(0.5, 3),   
  spend_Facebook_gammas = c(0.3, 1),
  spend_Facebook_thetas = c(0, 0.4),
  spend_Google_Search_alphas = c(0.5, 3),
  spend_Google_Search_gammas = c(0.3, 1),
  spend_Google_Search_thetas = c(0, 0.4),
  spend_TV_alphas = c(0.5, 3),
  spend_TV_gammas = c(0.3, 1),    
  spend_TV_thetas = c(0, 0.4),
  train_size = 0.7)



InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)


OutputModels <- robyn_run(
  InputCollect = InputCollect, # feed in all model specification
  cores = NULL, # NULL defaults to max available - 1
  iterations = 2000, # 2000 recommended for the dummy dataset with no calibration
  trials = 5, # 5 recommended for the dummy dataset
  ts_validation = TRUE, # 3-way-split time series for NRMSE validation.
  add_penalty_factor = FALSE # Experimental feature. Use with caution.
  )

OutputCollect <- robyn_outputs(
  InputCollect,
  OutputModels,
  #pareto_fronts = "auto",
  #calibration_constraint = 0.1, # range c(0.01, 0.1) & default at 0.1
  csv_out = "pareto", # "pareto" or "all"
  clusters = TRUE, # Set to TRUE to cluster similar models by ROAS. See ?robyn_clusters
  plot_pareto = TRUE, # Set to FALSE to deactivate plotting and saving model one-pagers
  plot_folder = "SiMMMulator_models", # path for plots export
  export = TRUE # this will create files locally
  )

```

## Environment & Robyn version
Make sure you're using the latest Robyn version before you post an issue.
- Robyn 3.9.0
- R version 4.2.1

**Comment by laresbernardo** [comment]
Hi @dmacoritto thanks for opening this ticket and sharing your comments.

> When running `InputCollect <- robyn_inputs(InputCollect = InputCollect, hyperparameters = hyperparameters)`, I get a warning that my exposure variable is not well correlated to my spend. Nonetheless, when running `InputCollect$modNLS$plots`, I see that all my R2 are above 0.94, so I do not understand why this warning is displayed.

AFAIK, siMMMulator adds noise and several transformations to the variables so that they are not as pure as the theoretical inputs you set. @njessica98 can you please validate this is the case? In Robyn we simply check the relationship between exposure and spend variables and if the correlation is below 0.8 we let you know and offer a couple 

> When launching the model `robyn_run`, I get this warning many times `Attention for loop i: manual decomp is not matching linear model prediction. Deviation is X%`. I have tried to figure out where does this come from, but I did not manage to find out.

This was fixed already some time ago. Can you please make sure you're running the latest Robyn version?

> Finally, and this is the most important point, none of the output models give results close to the ground truth (I know which channel has which weight as I set them up with the siMMMulator). I made sure the hyperparameters ranges include the true parameter value but my output models are pretty far off. So I would like to ask you if you have any advice on how to tune the MMM to be able to recover the true parameters.

I can think of a couple of reason this might be happening. You could add more iterations, broaden or close the hyperparameters ranges to follow what you know is real... Did you check if the near-solution is somewhere in one of the models? Also, remember we pick the best models based on 2 objetives, NRMSE and DECOMP.RSSD, so NRMSE that is originated from R2 is not the only factor considered. I'm really interested in getting to understand this case more.

FYI @gufengzhou @igorskokan

**Comment by njessica98** [comment]
Hi all! Oooh this is very interesting. I tried re-running your code with Robyn and realized that the hyperparameters (for adstock and saturation) in Robyn are for the spend variables and not the media variables themselves (impressions, clicks). siMMMulator applies these hyperparameters to the media variables directly. While hyperparameters for the spend and media variables should be related, I expect them to not be very highly correlated because a lot of noise has been added to convert spend to the media variables. 

I'm realizing that in the Robyn code, it says that this change happened with version >3.6.1. I think I might've created siMMMulator before then so I need to update this to match better. Let me put it in my next thing to do. Thanks for bringing this up!

As for the ground-truth for the ROIs of the media channels, Robyn should be able to get close-ish to those ground truth values that were revealed in Step 8 of siMMMulator. Were you able to get this result?

Also quick side note: You set base_p (baseline sales) to be 50,000 but the error_std to be 100,000 so you get some negative baseline sales for a few weeks. You may consider making the error_std smaller so you don't get as much volatility. I'm releasing a newer version of this in a few days that has an error message for this.

**Comment by dmacoritto** [comment]
Hello @laresbernardo ,

Thanks for your replies. Just to reply to your points.

1. I have rechecked and my point is that I actually get warnings that the fit is below 0.8 whereas it is actually much higher. I do not understand why this warning pops up.
2. Yes, I am working with the 3.9.0 version. I do not understand where this comes from.
3. I agree, I may have added a bit too much noise in the baseline. I will try to decrease it and try modeling again (thank you @njessica98 for pointing this out). Nonetheless, I believe using cross validation for time-series (using the ts_validation) is rather good practice, isn't it ?  Also, I think I should not tighten the hyperparameters range too much as the goal of this analysis is to find out whether Robyn can find out the true parameters while providing a real-case situation (in reality I do not know the value of the true hyperparameter, so I need to provide a range large enough to not exclude them). I will adapt the standard error in my baseline, rerun the modelization and keep you updated about the results.

Could you please have a look at the first two points as I think these are bugs rather than "methodology" questions?

Thank you

**Comment by laresbernardo** [comment]
Thanks for the additional context and comments. I think 1 and 2 are not actually bugs but problems with interpretation or versions. 

1. [Here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L659-L688) you can see the warnings system in which we simply check for the relationship between the spend and exposure metric for each paid channel. And [here](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L587-L657) we run a LM and a NLS using our `fit_spend_exposure()` [function](https://github.com/facebookexperimental/Robyn/blob/main/R/R/inputs.R#L846-L933), compare which one has a better fit, and warn the user with a possible improvement for the inputs based on the relationship (R2). Note that exposure values are not used for any other process within Robyn other than this.

2. Please, do try with latest dev version or CRAN version. We mistakenly started developing 3.9.0 without changing the version, so we might be talking of different timestamps of 3.9.0. Rest assured, those warnings won't happen because [they were commented](https://github.com/facebookexperimental/Robyn/blob/main/R/R/model.R#L1055-L1061) some time ago.

3. Let's wait for @njessica98 to deploy these new adjustments to siMMMulator and keep running these experiments. @njessica98 maybe enable a parameter so the user can pick if the transformations should be applied to exposure or spend variables, keeping "spend" as new default?

**Comment by gufengzhou** [comment]
> the hyperparameters (for adstock and saturation) in Robyn are for the spend variables and not the media variables themselves (impressions, clicks). siMMMulator applies these hyperparameters to the media variables directly.


Is it possible to apply hyperparameters on spends in siMMMulator? If yes then we might be able to get closer

**Comment by njessica98** [comment]
@gufengzhou , it's not currently possible. It's actually a pretty big rewrite to the code. So I can do it but it might take some time. I still think siMMMulator can be used to validate the ROIs on media channels, just not the hyperparameters.

**Comment by dmacoritto** [comment]
Hello everyone,
I have been trying to remove noise from the simulated inputCollect and do the test again to see if I could recover the true parameters (again with the SiMMMulator). I have really reduced the noise in the baseline and removed it completely from the channel's impact. I believed that removing the noise will make it easier to find the parameters correctly.

To run the MMM, the code is similar to the one I posted in my first post. My biggest issue is that all the reliable model outputs (one is completely unrealistic) from the robyn_outputs() functions indicate that the intercept is zero (has no impact). I have joined an example below from one of the outputs.

The R-squared is great, but I do not understand why the channels are "eating" all the baseline which we know amounts to 500'000$. This is already an issue I have encountered in real-life data. I would be really happy if anyone got an idea to correct that issue.

P.S. @laresbernardo, you were right about the `Attention for loop i: manual decomp is not matching linear model prediction. Deviation is X%` error. I guess it was a v.3.9.0 in Github is not the same as in CRAN. Thanks for your help on that point.

```
my_variables <- step_0_define_basic_parameters(years = 5,
                                               channels_impressions = c("Facebook", "TV"),
                                               channels_clicks = c("Google_Search"),
                                               frequency_of_campaigns = 1,
                                               true_cvr = c(0.01, 0.022, 0.05),
                                               revenue_per_conv = 3)


#Step 1 - Generate baseline


df_baseline <- step_1_create_baseline(
  my_variables = my_variables,
  base_p = 500000,
  trend_p = 0.2,
  temp_var = 16,
  temp_coef_mean = 1000,
  temp_coef_sd = 500,
  error_std = 800)


optional_step_1.5_plot_baseline_sales(df_baseline = df_baseline)

#Step 2 - Generate costs

df_ads_step2 <- step_2_ads_spend(
  my_variables = my_variables,
  campaign_spend_mean = 329000,
  campaign_spend_std = 60000,
  max_min_proportion_on_each_channel <- c(0.3, 0.35,
                                          0.2, 0.25))

optional_step_2.5_plot_ad_spend(df_ads_step2 = df_ads_step2)

#Step 3 - Generate clicks and impressions

df_ads_step3 <- step_3_generate_media(
  my_variables = my_variables,
  df_ads_step2 = df_ads_step2,
  true_cpm = c(2, 20, NA),
  true_cpc = c(NA, NA, 0.1),
  mean_noisy_cpm_cpc = c(0, 0, 0),
  std_noisy_cpm_cpc = c(0, 0, 0)
)

#Step 5 - Adding noise to conversion rates

df_ads_step4 <- step_4_generate_cvr(
  my_variables = my_variables,
  df_ads_step3 = df_ads_step3,
  mean_noisy_cvr = c(0.000, 0.000, 0.000),
  std_noisy_cvr = c(0.000, 0.000, 0.000)
)

df_ads_step5a_before_mmm <- step_5a_pivot_to_mmm_format(my_variables = my_variables,
                                                        df_ads_step4 = df_ads_step4)

#Step 5 - Adding decay effect

df_ads_step5b <- step_5b_decay(
  my_variables = my_variables,
  df_ads_step5a_before_mmm = df_ads_step5a_before_mmm,
  true_lambda_decay = c(0.2, 0.25, 0.1)
)


#Step 5 - Adding diminishing returns

df_ads_step5c <- step_5c_diminishing_returns(
  my_variables = my_variables,
  df_ads_step5b = df_ads_step5b,
  alpha_saturation = c(2, 2, 2),
  gamma_saturation = c(0.2, 0.25, 0.2)
)

#Step 6 - Calculating conversion

df_ads_step6 <- step_6_calculating_conversions(
  my_variables = my_variables,
  df_ads_step5c = df_ads_step5c
)

#Step 7 - A few more calculus

df_ads_step7 <- step_7_expanded_df(
  my_variables = my_variables,
  df_ads_step6 = df_ads_step6,
  df_baseline = df_baseline
)

#Step 8 - Get the ROI

step_8_calculate_roi(
  my_variables = my_variables,
  df_ads_step7 = df_ads_step7
)

#Final dataframe

df_final <- step_9_final_df(
  my_variables = my_variables,
  df_ads_step7 = df_ads_step7
)



optional_step_9.5_plot_final_df(df_final = df_final)
```


![image](https://user-images.githubusercontent.com/64702803/223976978-233bad26-8613-4007-8616-b6c6adf37fd6.png)
