### ISSUE TITLE
How to get granular ROI instead of Total ROI?

### ISSUE THREAD

**Issue by shamzos** [facebookexperimental/Robyn#636]
How can I get more granular results instead of the total ROI? For instance, is it possible to get the ROI for each month or quarter rather than the total ROI?

Thank you for your attention and support.

**Comment by bart-vanvlerken** [comment]
You can try to compute these yourself using the data in 'pareto_aggregated' or 'all_aggregated', which you can generate using robyn_outputs()

**Comment by shamzos** [comment]
@bart-vanvlerken Could you please elaborate with an example? Thank you.

**Comment by bart-vanvlerken** [comment]
The data in "pareto_alldecomp_matrix" contains the revenue as explained by the model, per period, decomposed into the different marketing channels and context variables included in the model. To get ROI for a given month/quarter, you could sum up the dep_var for the period of interest and then divide that by the amount of money spent during that period (which you can find in your raw data). To get even more granular, you could also do this by channel/context var by selecting the variables of interest instead of every variable. Hope it's clear! Here's a screenshot of what a pareto_alldecomp_matrix could look like:

![image](https://user-images.githubusercontent.com/118725564/222380981-2d512c64-c5cf-4b80-9fdf-85c1cbbd6b6c.png)

**Comment by shamzos** [comment]
@bart-vanvlerken  Yes thank you it's very helpful.
