### ISSUE TITLE
Specifying a range for train_size question

### ISSUE THREAD

**Issue by bart-vanvlerken** [facebookexperimental/Robyn#646]
Quick question to the developers, because I couldn't find an answer in the documentation: what is the reasoning for specifying a range of train_size and not a fixed value? I know it is possible to specify a fixed value, just wanted to know why specifying a range is also an option...

**Comment by laresbernardo** [comment]
Hi @bart-vanvlerken 

One of our main goals with Robyn is minimizing analysts' bias in "smart ways". When splitting the data we could fix a train size (say 80%) and continue the process as is, or let the user pick any value (based on X). But why .8 and not .7 or .75? Given we are iterating and building models by minimizing multiple errors (MOO) we don't want to set a single value that works for all time-series nor businesses. That is why we pass the train size as a hyperparameter so that nevergrad multi-objective optimization finds which train size minimizes the errors, thus one less (biased) decision on the hands of the analyst. And, as you can see in the time-series validation plot, even though when we provide a .5-.8 range, it doesn't always try to "overfit" by taking as much data as possible (.8) but finds an in-between value that works best for the optimizer.

![ts_validation](https://user-images.githubusercontent.com/25909073/224379309-e3e795af-b786-40b2-bdea-238a24924afb.png)

**Comment by bart-vanvlerken** [comment]
That makes sense! Thanks for the quick answer!

**Comment by SeanRichterWalsh** [comment]
This makes sense regarding removing potential bias in defining the split but with data points usually quite low for MMMs, even with daily data, have you ever considered that reducing sample size is problematic? Also, is there a case for not using ts_validation and just fitting the model to the data while checking the account residuals and R2? Thanks.
