### ISSUE TITLE
Using conversions

### ISSUE THREAD

**Issue by Tony-009** [facebookexperimental/Robyn#65]
Is there a way to project(forecast) the conversions based on the budget allocator recommendations?
--

A summary of what the issue is about.

Is there a way to project(forecast) the conversions based on the budget allocator recommendations? As budget allocator tells you the initial conversions one can expect so can we replicate that for the next few months? I am looking at the file 1_1_1 reallocated and pareto_aggregated but having a hard time understanding how to mean spend/mean responses, initSpendUnitTotal,initResponseUnit are calculated then maybe I can do that. Although I looked at the function code and I was able to find some but any input or recommendation is deeply appreciated

# Steps to Reproduce

Please provide instructions that can be used to reproduce your issue. Usually this will include a test case that produces the wrong output.

# Expected Behavior

What you expected to happen. For example the error message you expected to see.

# Actual Results

What actually happened. For example, an error message you did not expect to see.

# Environment

R 4.03

**Comment by gufengzhou** [comment]
hey, first of all, there's been a bug introduced by the sorting issue from the data.table library that is fixed just now. please use the latest update. optmResponseUnit

Regarding "forecast the conversion", it's done in the budget allocator already. Looking at the example plot in readme, the lower left plot from the _reallocated.png tells you how much of the response (conversions in your case) will increase or decrease per time unit (if you use weekly data, it'll be the change of a week). It's basically saying this: according to your input data and the model you choose, if you shift media budget as recommended, you will expect this much of change in response (conversions) within a week. This is the column initResponseUnit in the _reallocated.csv 
![image](https://user-images.githubusercontent.com/14415136/115450769-a078fe00-a21c-11eb-8611-575820b43708.png)

**Comment by Tony-009** [comment]
Okay! Yes, that makes sense. I was also looking to see how the mean_spend and mean_reponse were calculated? because that will provide a point of reference(initial attributed conversions) for the expected change in conversion/sales for the future weeks. Appreciate the help!

**Comment by gufengzhou** [comment]
mean_spend is the mean of all non-zero periods within modelling window. for example, if you have 365 days of data and a new channel is only active since 30 days, then the mean_spend for this channel will be the mean of the 30 days. mean_response is bit more complicated. if it's spend representing the channel, then the pseudo-code is mean_response =  hill_function(mean_spend)*ridge_beta_coef. If it's exposure representing the channel, then pseudo-code is mean_response =  hill_function(reverse_michaelis_menten(mean_spend))*ridge_beta_coef. Basically, the mean_spend has to go through all transformation to get to mean_response. In the current .func script, it's row 1771- 1839. hope it helps.

**Comment by Tony-009** [comment]
Okay! Thanks for the in-depth response. This is exactly what I was looking for because something wasn't adding when I was looking at the code and trying to understand the mean_response. Anyways, Appreciate the time and help:-)
