### ISSUE TITLE
Remove the intercept

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#669]
Hi, Is it possible to remove the intercept? How? Thank you!!

**Comment by laresbernardo** [comment]
Hi @AlessioPallotti 
- Can you please share with us your use case and the reason you want / need to remove the intercept?
- Yes you can. By setting `intercept = FALSE` and passing it via the `...` parameter in `robyn_run(...)`, we'll pass it to `glmnet(...)` and it should remove the intercept. Can you confirm that's the case?

**Comment by AlessioPallotti** [comment]
Great it works! Thank You!

**Comment by laresbernardo** [comment]
Would you mind giving us a bit more context on this specific use case? Feel free to close this ticket afterwards.

**Comment by banalytics** [comment]
@laresbernardo It's an older one, but an example for where I removed the intercept was a subscription business where recurring revenue essentially constitutes base sales. I ended up only using new subscription revenue in the model since the results I was getting with including the recurring revenue in the model hoping it would get modelled as base sales were subpar (based on comparing the plot of predicted vs actual as R-2 without intercept is inflated).
