### ISSUE TITLE
Cannot run optimizer

### ISSUE THREAD

**Issue by famendez7** [facebookexperimental/Robyn#67]
Trying to run **budget allocator function** and getting this error:

**Error in names(channel_constr_low) <- set_mediaVarName : 
  'names' attribute [6] must be the same length as the vector [1]**

I am giving the function the following:
f.budgetAllocator(modID = "2_16_3",
                              ,optim_algo = "MMA_AUGLAG"
                              ,expected_spend = NULL
                              ,expected_spend_days = NULL
                              ,channel_constr_low = 0.5
                              ,channel_constr_up = 2
                              ,scenario = "max_historical_response"
                              ,maxeval = 100000
                              ,constr_mode = "eq")

if **channel_constr_low** is an integer, why is the function applying **names()** to it ?

Thanks!

Federico

**Comment by Leonelsentana** [comment]
Hey Fede,

Hope you are well and thanks for trying our code. Let me show you a best practice example so that you copy it on your end:

```
model_output_collect$allSolutions
optim_result <- f.budgetAllocator(modID = "2_16_3" # input one of the model IDs in model_output_collect$allSolutions to get optimisation result
                                  ,scenario = "max_historical_response" # c(max_historical_response, max_response_expected_spend)
                                  #,expected_spend = 100000 # specify future spend volume. only applies when scenario = "max_response_expected_spend"
                                  #,expected_spend_days = 90 # specify period for the future spend volumne in days. only applies when scenario = "max_response_expected_spend"
                                  ,channel_constr_low = c(0.25, 0.25, 0.25, 0.25, 0.25, 0.25) # must be between 0.01-1 and has same length and order as set_mediaVarName
                                  ,channel_constr_up = c(3, 3, 3, 3, 3, 3) # not recommended to 'exaggerate' upper bounds. 1.5 means channel budget can increase to 150% of current level
)
```
Please note to just comment the lines for expected_spend and expected_spend_days as well as, putting unoe channel_constr_low and one channel_constr_up per each channel involved. In the example above we have 6 channels to assess.
Names is used basically to see if the number of channels listed in the optimization actually match the ones that are used in the budget allocator.

Let me know if that works,
Hope it helps!
Thanks,
Leo

**Comment by famendez7** [comment]
It worked, makes sense that channel_constr_low should be a vector.

Thanks Leo!
