### ISSUE TITLE
optmResponseUnitTotal doesn't seem to be working correctly in robyn_allocator output

### ISSUE THREAD

**Issue by tingwei-lin** [facebookexperimental/Robyn#677]
## Describe issue
optmResponseUnitTotal doesn't seem to be working correctly in robyn_allocator

optmResponseUnitTotal stays the same after lowering the total_budget to a certain amount in the output of robyn_allocator. For example, optmResponseUnitTotal equals to 27 when trying both $1000 and $500 as total_budget.

## Provide reproducible example

```
AllocatorCollect <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  scenario = "max_response",
  total_budget = 400,
  date_range = 'all',
  export = TRUE
)

AllocatorCollect2$dt_optimOut
```

## Environment & Robyn version
Robyn version: ‘3.10.1.9000’
R version: "R version 4.2.2 (2022-10-31)"

**Comment by gufengzhou** [comment]
This is because your constraints are too strict, so you can't really spend up that money. Try loosen / widen your lower and upper constraints and you'll see different results. We also have the warning in the console:
`NOTE: Given the upper/lower constrains, the total budget can't be fully allocated (^)`
