### ISSUE TITLE
Bias (ie non zero average residuals) for pareto-optimal models with example data

### ISSUE THREAD

**Issue by lorenze3** [facebookexperimental/Robyn#69]
# Contributing to FB NextGen MMM R script

# Issue

The residual plots in documentation and produced when I run the example locally show a non-zero average residual for all output models.

# Steps to Reproduce

Follow the example in the documentation

# Expected Behavior

Ideally, 'optimal models' would have near-zero average error in prediction.  This particularly important for business users that will test the results of a recommended budget allocation against the model's prediction.

With that in mind, the question becomes if it is necessary, and if so how shall we, adjust the response coming out of the biased model prior to running the optimization.

**Comment by lorenze3** [comment]
Mean to add -- Thanks to the team for releasing this!  I love a lot of what is going on here, and I may use this as is (or possibly with some modifications . . .) in my current role.

**Comment by gufengzhou** [comment]
hey thanks for flagging this! we're also just looking into this since couple of days. turns out that it's a visualisation bug: the intercept is not included in yhat and thus the larger the intercept the further the residual plot is above 0. Will push the fix this week. sorry for the irritation and thanks again.

**Comment by gufengzhou** [comment]
This is fixed by last commit so closing this
