### ISSUE TITLE
How are computed the "contribution" in Robyn 

### ISSUE THREAD

**Issue by CherifY** [facebookexperimental/Robyn#692]
## Describe issue
Hello ! In my search to contruct a MMM model I found Robyn ! It is interesting because we have a complete procedure and moreover the math are clearer than what I have seen in other ressources. However I have a question about the Outputs : Response decomposition waterfall by predictor. How are computed the contribution for each variable ? In linear regression I know that we can recover this from 

$$ \beta_i \times x_{i,t}$$

However here I don't see by what is multiplied $x_{i,t}$ ? It is a contribution based on the data so we multiply each times by the value of our explanatory variable wich would be surprising since we already know the original contribution and it would be a contribution in average which is not mentioned ?

Thank you a lot !

**Comment by gufengzhou** [comment]
Hi, what do you mean by "we already know the original contribution"? We're running a model precisely because we don't know the media contribution. Or am I misunderstanding you?

In general, beta is the coefficient that is an average over the modelling period and xi,t is the transformed media variable i at time t. The trick here is that xi,t = f_saturation( f_adstock (x_raw_i,t). Twice transformed before the fitting.

**Comment by CherifY** [comment]
Hi ! First, thank you to take the time to answer my post. By  "we already know the original contribution" I meant that with the data we already know the share of each explanatory variable in the sale's volume (except for the media specific variables which are in the form of GRPs or others) just by doing the value of the explanatory variable divided by the total sales volume but it has no sense since variable are not in the same unit, right ?

This leads to the following questions : 

- how contribution is computed here, since the variable are not necessarily in the same unit, would it make sense to do $$\beta\times x $$ if it is what does Robyn ? 


-  Assuming that the calculation method of the previous question is the one performed by Robyn for the contribution, how does it works when the model is not linear but we have a multiplicative model like 
$$ y_t = \beta_{0}\Pi_{i=1}^{K}x_{i,t}^{\beta_i}\times e^{\sum_{l=K+1}^{L}\beta_l x_{l,t} }$$ since in the Robyn documentation when presenting the ridge regression I think the functional form is not necessarily fixed or am I wrong and we need to stick to the linear case ? 

(sorry for the expression I don't know why it is does not display in latex) 

Thank you a lot !

**Comment by gufengzhou** [comment]
As mentioned above, the contribution of media1 is computed as beta1 x media1_transformed = beta1 x f_saturation( f_adstock (media_raw). In Robyn, we require users to always provide spend for media and always use spend to fit the model, while exposure variables (GRP, impressions etc) are only used as support metrics. 

Again, I don't understand / agree that "we already know the share of each explanatory variable in the sale's volume", because media contribution on sales IS the result from MMM. Otherwise, if there's already source of truth about media contribution, there's no need to model it. 

Regarding multiplicative model, it's not supported in Robyn now. Robyn is additive only and the decomposition, or the calculation of the contribution, is based on this additive nature and as explained above. For multiplication, the decomposition would be completely different, because the betas are not the effect size anymore.

**Comment by CherifY** [comment]
Thank you for your answer ! For the second point, you're right, what I had in mind was wrong : with the explanatory variable (marketing channel) we do not have the sales volume generated by this channel and so we cannot just do a simple ratio with the total sales volume and this is exactly why we are doing MMM, I got confused on this and thank you for clarifying this point with your second paragraph I think I am OK on this now. 

Concerning the multiplicative model this seems clear indeed that we cannot interpret the beta as the effect size anymore since the function is far mor complex with the exponents parameters and the exponential.  Now if we decide to take the log to both side of the multiplicative model, we "rescale" (from the log) the dependent variable and we obtain someting linear in $log(x_{i,t})$ and in $x_{l,t}$ no ?  So the idea will be to replace in the original dataframe the corresponding variables by their logs (including the dependent variable)  and let the variable not transformed as initial and then use Robyn with the transformed dataframe in order to get a decomposition ? I would like to have your advice on my way to get around the problem.  It will leads us to work on the log of the dependent variable instead of the dependent variable itself but I don't think it is a problem since the log is just a "rescale" of the magnitude from a mathematical point of view preserving the initial variable in some way (since the function is monotonic no ?) 

Thank you a lot for your comprehension

**Comment by gufengzhou** [comment]
You want to test log log models? The interpretation of the coefficients completely changes (lots of answers on Google), meaning current decomposition won't work. Robyn doesn't support this so far.
