### ISSUE TITLE
Robyn Adj. R2 Train | Val | Test not seem logical 

### ISSUE THREAD

**Issue by zeynepcanbulat** [facebookexperimental/Robyn#696]
-Project Robyn

Hello, when I run Robyn project, I always get a negative R2 of (for instance) test meanwhile the others are pretty high. Similarly, when I get high R2 of validation and test, R2 of train is negative. I never get a R2 of validation, test and train scores that are high and positive at the same time. One of them is always negative or 0 meanwhile the others are above 90%. 

-Environment & Robyn version

Robyn version: 3.9.0
R version: 4.2.2

**Comment by gufengzhou** [comment]
Hi, this sounds strange indeed. We haven't seen this sofar. Can you share bit more details about the different models? Esp. the actual vs. fitted plot? 

The adjusted Rsq could be negative for above 1 due to the way how adjusted Rsq is calculated and when the fit is really bad. But I haven't seen any consistent pattern as you mentioned.

**Comment by SeanRichterWalsh** [comment]
Hi. I have seen a similar situation in a use case. Do you mean ts validation is not needed unless you want to predict (which Robyn does not allow currently)? Essentially, just fitting the model to the entire dataset and explaining variance with it. It is good to know if such a model generalises well to unseen data but it is not absolutely necessary. Is my understanding here correct? Thank you.
