### ISSUE TITLE
There is a bug when I try Quick start.

### ISSUE THREAD

**Issue by watanta** [facebookexperimental/Robyn#7]
# Issue
There is a bug when I try Quick start.
I run fb_nextgen_mmm_v20.0.exec.R.
In Line139, 
`dt_mod <- f.inputWrangling() `
 I got
`Error in f.inputWrangling() : week start has to be Monday or Sunday
In addition: Warning messages:
1: In value[[3L]](cond) :
  default start value for nls out of range. using c(1,1) instead
2: In value[[3L]](cond) :
  default start value for nls out of range. using c(1,1) instead`

Then I command 
`dt_mod`
I got
`Error: object 'dt_mod' not found`

# Steps to Reproduce

- run fb_nextgen_mmm_v20.0.exec.R

# Expected Behavior
- `dt_mod` is made

# Actual Results
- `dt_mod` is not made

# Environment
`platform       x86_64-w64-mingw32            
arch           x86_64                        
os             mingw32                       
system         x86_64, mingw32               
status                                       
major          3                             
minor          6.0                           
year           2019                          
month          04                            
day            26                            
svn rev        76424                         
language       R                             
version.string R version 3.6.0 (2019-04-26)  
nickname       Planting of a Tree  ` (R --version)

**Comment by gufengzhou** [comment]
Hey @watanta, thanks for trying out! The warning "week start has to be Monday or Sunday" indicates that you're using weekly time series and the dates are not Monday or Sunday. Can you check if this is the case? Because in order for Prophet to correctly create seasonal and holiday variables, it only allows Monday or Sunday as week start. If your input data is not on Mo/Su, you have to transform it to Mo/Su. Let me know if your input date is correctly and the issue still occurs.

**Comment by m4x3i5** [comment]
I ran into the same error when running the fb_nextgen_mmm_v20.0.exec.R file with the data from the de_simulated_data.csv file.
I think it is related to these two lines in the `f.inputWrangling` Function:

```
weekStartInput <- weekdays(dt_transform[1, ds])
weekStartMonday <- if(weekStartInput=="Monday") {TRUE} else if (weekStartInput=="Sunday") {FALSE} else {stop("week start has to be Monday or Sunday")}
```

When you run the code from a non-English location the system locale is usually non-English and the `weekdays` function will return the weekdays in the language of the system locale. 

I suppose you could try changing the system locale by something like this in R:
`Sys.setlocale("LC_TIME", "English")` 

See this stackoverflow question for getting weekdays in English: 
https://stackoverflow.com/questions/17031002/get-weekdays-in-english-in-r

To avoid this error in the future, maybe you could use `lubridate::wday()` to return the day of the week as a number and check for that instead of the weekday name.

**Comment by watanta** [comment]
@m4x3i5 Thank you very much! It may be. I'm using the Japanese version of R.
I will report the result when I try it.

**Comment by watanta** [comment]
@m4x3i5 Thank you! It worked!!!

I thought this should be added to the code, so I threw a pull request.

https://github.com/facebookexperimental/Robyn/pull/8

**Comment by gufengzhou** [comment]
Thank you all! Apparently we didn't take the difference between languages into account. We'll definitely include this into the next update.
