### ISSUE TITLE
# Issue

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#71]
Hi,

Hope you are doing well,

When I run the code to "dt_mod <- f.inputWrangling()", there is an error that "Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates". Could you please tell me how to fix it and reason? Thank you so much

Best,

**Comment by gufengzhou** [comment]
Hi, are you testing with our simulated data or it's your own data? It happened before to other users. Please refer to this thread and see if there's any similarity? https://github.com/facebookexperimental/Robyn/issues/27

**Comment by wenyanyy** [comment]
@gufengzhou Hi gufengzhou, Thank you for your responding, I saw the #27 and fix the code as you wrote. the error has been fixed. thanks. 

But I have one more questions. For setting each hyperparameter bounds, do you have reference to set them? for example,"ooh_S_alphas = c(0.5, 3)", how do i know the bound is between 0.5 and 3? is it right that different media channel alphas has different bounds?

Thanks~~

**Comment by gufengzhou** [comment]
alpha and gamma are the two parameters for the saturation curve transformation, where alpha controls the shape of the curve (S/L shape). If you run the support function f.plotResponseCurves(T), you'll see an example plot of how alpha and gamma work. For alpha, smaller alpha means L shape and larger alpha S shape. We've recommended alpha to be between 0.5 - 3 out of our experience, because below 0.5 or above 3 the respective L and S shapes get so extreme that it won't be realistic for MMM/business context. We recommend to use these bounds, but of course you can change them and check it yourselves. For alpha and gamma, we have the same bound recommendation for all channels, because we believe the bounds are quite wide already and usual business saturation should be included already.
![image](https://user-images.githubusercontent.com/14415136/116566748-4e646680-a907-11eb-8fe1-e8f27934d362.png)
