### ISSUE TITLE
Removing intercept from robyn_run

### ISSUE THREAD

**Issue by NicolasMatrices-v2** [facebookexperimental/Robyn#722]
Hi, I tried following this issue's solution https://github.com/facebookexperimental/Robyn/issues/669 and include these parameters in robyn_run, but the intercept is still appearing as the top contributor in Robyn's one pager waterfall plot.

Could somebody shed any insight as to how I could remove the intercept if this does not work?  cc @gufengzhou @laresbernardo

**Comment by laresbernardo** [comment]
This seems to be a bug given we are passing the `intercept` parameter through the `...` and when passing `...` within the parallel computing, it's not being passed. Previously this issue didn't happen because we hadn't built a function to pass the parallel computing using `...`. Give me some time to think of a way of passing this double lazy eval into the parallel computation and into `glmnet`.

**Comment by laresbernardo** [comment]
@NicolasMatrices-v2 would you mind updating to latest dev version and retry using the new parameter `intercept = FALSE`? It's now working on my end.

**Comment by NicolasMatrices-v2** [comment]
@laresbernardo thanks so much for the fix! This works now : ) Closing the issue.
