### ISSUE TITLE
Simulation for GRP at campaign and format level

### ISSUE THREAD

**Issue by AlessioPallotti** [facebookexperimental/Robyn#733]
Hi,
Based on the data I have, I have the GRPs and the corresponding investments. My aim is to carry out simulations by level of granularity of GRP campaigns and/or by GRP format. At the input level, how do we input the information? Also, how do I run the simulations simultaneously by both GRP format and campaign?

Thank you very much!

**Comment by laresbernardo** [comment]
Hi, as explained a bunch of times in different tickets ([1](https://github.com/facebookexperimental/Robyn/issues/727#issuecomment-1546282846), [2](https://github.com/facebookexperimental/Robyn/issues/466#issuecomment-1226678875), [3](https://github.com/facebookexperimental/Robyn/issues/656), ...), we model using spend data only, not exposure (like GRP, impressions, etc). We do this because when optimizing budget allocation we have a 1:1 relationship with CPA or ROAS and no need to transform the variables (once again) thus avoiding additional unnecessary noise.
That said, you could model exposure metrics by setting these exposure metrics as `paid_media_spends` but the allocator functionality would be invalidated because we'd be optimizing towards metrics that are not comparable (GRP are quite different that impressions and so on).

**Comment by AlessioPallotti** [comment]
Thank you very much for your answers. 
Let me explain my problem in detail: as far as TV is concerned, I only have the overall investment, but I also have the detail per channel, format, seconding etc (I do not have the investment in this detail though). My intention was firstly to run a model considering the total investments per TV. As a second step, I would like to find a way to get the curves for the GRPs on the 4 details for which I do not have the investments, so instead of considering the investments consider the grps. Is there a way to fix the parameters of the first model? My goal is to reweight the overall TV investment for the 4 levels of GRPs for which I don't have the investment detail, while still considering the effect of all other variables. Do you have any advice?

**Comment by gufengzhou** [comment]
I'd recommend you to extrapolate your total investment into granular dimensions using the weights from your GRP breakdowns.
