### ISSUE TITLE
Total response in Budget allocation 

### ISSUE THREAD

**Issue by ghltk** [facebookexperimental/Robyn#734]
I'm trying to understand the new version of the budget allocation One-Pager. 
How was total response calculated? 

As you can see the plot below, my Initial total response is 17.3M. 
If I summarize the paid media values from 'pareto_alldecop_matrix', they do not match.(I got 21.8M)
Is this the correct way to calculate it?

![image](https://github.com/facebookexperimental/Robyn/assets/131640422/ed905a9a-2165-4eb7-b4ce-e33e41390fcd)
![image](https://github.com/facebookexperimental/Robyn/assets/131640422/b470bb4c-b9cb-4dc4-abfc-aa05eb0b6b2f)

Thank you

-Environment & Robyn version
Robyn version: 3.10.3.9000
R version 4.1.3 (2022-03-10)

**Comment by laresbernardo** [comment]
Hi @ghltk Would you mind reading these 2 posts to have a much better understanding on what's happening under the hood for the budget allocation process?
- 1) [The convergence of marginal ROAS in the budget allocation in Robyn](https://medium.com/@gufengzhou/the-convergence-of-marginal-roas-in-the-budget-allocation-in-robyn-5d407aebf021)
- 2) [Hitting ROAS target using Robyn’s budget allocator](https://medium.com/@gufengzhou/hitting-roas-target-using-robyns-budget-allocator-274ace3add4f)

Short answer to your question: the total response includes the effect from adstock and raw spend together.

**Comment by mikezgit123** [comment]
@laresbernardo We are also experiencing the same situation as @ddempseyr and @ghltk have above where the "total response" from the initial allocator output is far less than the sum of sales driven by the media variables only from the pareto all decomp matrix output for the same date range.

We have read both the medium articles but it is not clear why the two are so far apart.  Are you saying that the original Robyn output accounts for adstock while the allocator is only accounting for the immediate purchases driven by each channel from the immediate vs carryover analysis?

**Comment by ChrisHaferl** [comment]
I am also seeing this mismatch in ROI between the one-pager model output and budget allocator output for the 'Initial' case.

**Comment by RanM23** [comment]
> @laresbernardo We are also experiencing the same situation as @ddempseyr and @ghltk have above where the "total response" from the initial allocator output is far less than the sum of sales driven by the media variables only from the pareto all decomp matrix output for the same date range.
> 
> We have read both the medium articles but it is not clear why the two are so far apart. Are you saying that the original Robyn output accounts for adstock while the allocator is only accounting for the immediate purchases driven by each channel from the immediate vs carryover analysis?

I'm experiencing the same situation where the total response from the initial allocator is far less than the sum of response driven by the media variables for the same date range. Also not sure how the adstock is considered or to be calculated into the total response from the initial allocator. Any examples? Thanks! @laresbernardo

**Comment by gufengzhou** [comment]
Hi all, sorry for the delay. 

- Difference between the ROAS in model onepager and allocator onepager: The model onepager shows the total ROAS in the entire modeling window, which is calculated as total_roas = sum(response_d1, resp_d2 .... resp_d100) / sum(spend_d1, ....).  On the other side, the allocator onepager shows the ROAS in the latest 4 weeks by default. We should provide clearer info in the plots, sorry for that.
- To the top thread question from @ghltk , very good observation. In your table, you're summing up the historical responses of the last 4 weeks, which is totally correct and it's the number you will report. However, this works differently in the allocator. I can't use 4 different saturation positions (each week has it's own saturation point in the history). I need to define an average spend level as well as the average adstock level within the last 4 weeks for the allocation to work. After getting that avg. saturation position, I will get the response on that, then multiply that by 4. Therefore, the allocator rather uses a simulated response based on the pattern of the last 4 weeks instead of the historical response. 

I know this is not very intuitive. We'll try to improve the interpretation in the future.

**Comment by mikezgit123** [comment]
@gufengzhou Appreciate the response.  Also, thank you for all your hard work on this wonderful project (@laresbernardo you too)!

The idea that this is a directional simulation makes sense.  In this case, it seems it would be fair to take the +% Response from the allocator and apply that % to the base from the original output to re-calculate the total response.  Doing so in the first example here, $21,884,980 * 1.152 = $25,211,497 meaning the allocation would have driven an incremental $3.3M ($25.2M - $21.9M) in sales as opposed to the $2.6M the allocator output says.  This is all looking at the first Bounded output.  Please correct if I'm missing a reason this isn't a fair play.

Switching gears a bit, I'm curious why the need to take an average as opposed to running each timeframe on it's own and then adding them up?  In your example of weekly data with the default setting of 4 weeks it doesn't seem like it would be that big of a deal.  Daily data and longer timeframes might become computationally heavy, however.  I'm sure I'm not accounting for something more complex under the hood.  If that's the case, I'd love to be educated on what I'm overlooking.

Thanks again!

**Comment by mtodisco10** [comment]
I'm also trying to settle the difference between the historical responses in pareto_alldecomp_matrix and the output from the allocator.  Is @mikezgit123 logic sound in applying a percentage?  Is there a way we can do this by channel rather than an overall total?  

Any additional info on this subject would be appreciated.  Thanks!

**Comment by gufengzhou** [comment]
FYI i just pushed a fix on this. Please check [this comment](https://github.com/facebookexperimental/Robyn/issues/772#issuecomment-1647436681) how to validate yourself. Update the dev package first of course.

**Comment by tgtod002** [comment]
@gufengzhou .  You mentioned that the default ROAS for allocator is last 4 weeks.    Does this happen even if you put  a date range of last_52?   

I am still trying to reconcise the model One pager, vs the Allocator one pager.

ROI was 3.68, 2.48, and 
ROAS in the allocator is 0.7, 

![image](https://github.com/facebookexperimental/Robyn/assets/69650410/5fb4ce7b-fa77-4565-a604-dbefde543440)



![image](https://github.com/facebookexperimental/Robyn/assets/69650410/3673a8fe-b798-4bfe-9177-708caf76d21c)

the following is my input....
AllocatorCollect2 <- robyn_allocator(
  InputCollect = InputCollect,
  OutputCollect = OutputCollect,
  select_model = select_model,
  date_range = "last_52", 
  total_budget = 4800000, 
  channel_constr_low = c(0.7, 0.7),
  channel_constr_up = c(1.5, 1.5),
  channel_constr_multiplier = 5, # Customise bound extension for wider insights
  scenario = "max_response",
  export = create_files

**Comment by gufengzhou** [comment]
Have you checked this? https://github.com/facebookexperimental/Robyn/issues/772#issuecomment-1647436681

**Comment by gufengzhou** [comment]
feel free to reopen if necessary

**Comment by shubhamjain1142** [comment]
@gufengzhou is this fix on budget allocator roas vs one-pager roas available in v3.10.5 i.e. the latest cran release version?

**Comment by gufengzhou** [comment]
the fix is still on github, not CRAN
