### ISSUE TITLE
Holiday as dummy?

### ISSUE THREAD

**Issue by retiuk** [facebookexperimental/Robyn#76]
Hi guys, even after including the holidays file you supplied, I am still having big underpredictions in xmas week (xmas peaks are quite noticeable).

I tried adding a dummy variable in xmas week in the baseline group of variables but the model drops it (coef=0).
What is the correct way to add a dummy variable? or, is there a way to make the prophet holiday capture these peaks?

Thanks very much,

F

**Comment by gufengzhou** [comment]
How many years of data do you have? Are you using trend, season and holiday from Prophet? In case of More than one Xmas included in the data (and there is repeating pattern of course), season from prophet should be able to capture that. If not, and in case you are expecting peaks in for example Dec.24-31, one idea might be manually adding all days Dec.24-31 into the holiday csv, so that this will be also captured by the holiday variable from prophet.

**Comment by retiuk** [comment]
@gufengzhou thank you! Apparently I needed to have the exact observed dates in the holidays file. Now the prophet holiday variable is capturing the peaks.

**Comment by retiuk** [comment]
Any idea why the holiday variable is driving volume in all weeks? Even weeks I don't have a holiday in holidays.csv ?

![image](https://user-images.githubusercontent.com/35783806/117290068-46f01080-ae65-11eb-929f-a78b9c6cf955.png)

**Comment by gufengzhou** [comment]
Hi, first of all please check [prophet's documentation](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html) for more customised ways of using holidays, for example using lower_windows and upper_windows in the holidays.csv to account for holiday periods. Regarding volumes in non-holiday weeks, it's actually just me linearly transformed the original holiday variable to positive to avoid potential difficulty in decomposition and interpretation later. The variance of holiday won't change by this transformation and the latitude will be adjusted by the beta coefficient anyway. 
![image](https://user-images.githubusercontent.com/14415136/117792034-3667dd80-b24b-11eb-93ad-50f0fa5c0a28.png)
