### ISSUE TITLE
Reach equation (Michaelis-Menten)

### ISSUE THREAD

**Issue by retiuk** [facebookexperimental/Robyn#77]
Hi team, have been reviewing the Robyn methodology behind the reach calculation and I have one suggestion and one question you might find useful:

1) How is the model taking into account the penetration (max reach) that is inherent to the media channel? e.g. OOH penetration much higher than Social.
Think you might need a penetration parameter (%) that varies by channel and multiplies the adstocked media to get the reach, rather than using the 'MediaCostFactor' that nothing really tells you about the size of your target audience.

2) In this line of code:
`nlsStartVal <- list(Vmax = dt_spendModInput[, max(reach)/2], Km = dt_spendModInput[, max(reach)])`

Shouldn't be the other way around?
Vmax = max(reach) and Km = max(reach)/2 ?
Given how the Michaelis-Menten equation is defined:[https://en.wikipedia.org/wiki/Michaelis%E2%80%93Menten_kinetics](url)

Thank you!

**Comment by gufengzhou** [comment]
Hi, thanks for your suggestions!
1. When talking about penetration of the population, then we're inevitably also entering the area of "viewability", which is a whole topic of itself. We believe that due to the nature of regression, the latitude of the variable doesn't really matter (no matter if 100€ or 1Mio€ spend, or 10k imp or 10mio imp, 10 GRP or 500 GRP). It's the variance of the time series that explains the dependent. This is also why you could have the smallest channel getting the most effect, if the correlation is strong. Robyn corrects this by using the DECOMP.RSSD in hyperparameter optimisation and thus takes care of the latitude of the media channels already. The variable 'MediaCostFactor' is actually not really in active use and could be actually deprecated.
2. Regarding the MM function, you probably got me :) It's maybe not too bad because it's just the starting values of the nonlinear optimisation. Nevertheless I'll have a deeper look and probably change it. Thanks!
