### ISSUE TITLE
ROI scale difference in Conversion and Revenue

### ISSUE THREAD

**Issue by sujithnair2021** [facebookexperimental/Robyn#80]
# Issue

Why are ROI values very different for revenue vs conversion? I assumed it is a calculation comparing effect share and spend share. I see similar values for spend vs effect share; but mean roi is 0.005 for conversion, while its 1.2 for conversion with same spend variables.

**Comment by gufengzhou** [comment]
I don't quite get what you mean. Can you share some screenshots? But in general, when using conversions as dependent variable, ROI becomes conversions/investment instead of revenue/investment. For example, assuming 1Mio spend, 2Mio revenue and 20k conversions (meaning 100$ revenue per conversion), we'll get 2 as ROI for revenue and 0.02 ROI for conversion, simply because of the relationship above. Makes sense?

**Comment by Leonelsentana** [comment]
Hi @sujithnair2021, I believe you are referring to the difference in ROI in conversions vs. sales. It is expected that conversions will have always very small amount for conversion just as Gufeng explained the ROI for conversions will be the marginal contribution of each dollar spent into additional conversions. The fact that you get 0.005 conversions per dollar spent means that you will be needing $200 dollars to obtain one conversion via that channel. Whereas, the ROI for revenue would be that you obtain 1.2 dollars in return per each dollar spent. This means very likely that the return is positive and that from the $200 dollars you could invest to get one conversion, you would be getting an average revenue of $200 x 1.2 ROI= $240 dollars of revenue per conversion. Hope it helps :)

**Comment by sujithnair2021** [comment]
Makes sense! Thanks!!
