### ISSUE TITLE
how to calculate avg effect and spend share?

### ISSUE THREAD

**Issue by xsmile10000** [facebookexperimental/Robyn#83]
Hi thanks for your great work.
Here is my question:
It seems that the avg spend share is not the real spend share (spend by channel / total spend).
can you share the formular to calculate avg effect and spend share? Thanks.

**Comment by gufengzhou** [comment]
avg spend is the avg of non-zero periods. If you have 100 days in model, but one channel has only spent money in last 20 days, then the average daily spend of that channel will be sum of all spend divided by 20 instead of 100. The intention behind is to reflect the real spend level when you really spent money. Then avg response = coef*hill(adstock(avg_spend)), more or less

**Comment by xsmile10000** [comment]
clear， thanks a lot.
