### ISSUE TITLE
Any sugguestion on Synergy analysis?

### ISSUE THREAD

**Issue by xsmile10000** [facebookexperimental/Robyn#84]
Hi， sorry to bother you again.

Sometimes, we want to analysis cross channel effect, can i just add a total spend of multiple channels as another x?
do you have any suggestion on this? Many thanks.

**Comment by gufengzhou** [comment]
hi, no worries, ask as many questions as you want:) x-channel effect is usually solved by adding multiplicative term instead of pure additive (which is what Robyn has now). As pseudo code it would be response = coef1*chnl1 + coef2*chnl2 + coef3*chnl1*chnl2 ... --> the third term is the interactive effect of both channels. As you can imagine it's bit more complicated, esp. the decomposition of the interaction is not super clear. We'll consider adding interaction in the future. For the moment, Robyn is only additive

**Comment by xsmile10000** [comment]
Got it, thanks.
