### ISSUE TITLE
Robyn trial runs have started to get very long

### ISSUE THREAD

**Issue by Owakelz** [facebookexperimental/Robyn#847]
Hi there!

My Robyn run is taking an extremely long time with some trials (>1Hour). My dataset is 191 weeks by 61 variables, we were running with 5 trials, 5000 iterations and 12 pareto fronts. This could be hardware issue but just checking here for guidance on the setup or whether there could be a software issue to check. The latest run is where the issue occured, it was running faster with previous runs on the same settings and same dataset.

**Comment by bart-vanvlerken** [comment]
Strange! Usually a change in the settings would cause this. But I must say, one hour for 5k iterations and a dataset of that size is not out of the ordinary in terms of length. It could also be caused by your computer having to share computing power with other applications that were active during the run.

**Comment by gufengzhou** [comment]
61 vars are quite a lot, we usually recommend column to row ratio of 1:10 as best practise. bit lower is ok but 1:3 is very extreme. 
regardless, was it faster before?

**Comment by gufengzhou** [comment]
please reopen if necessary
