### ISSUE TITLE
How to replicate the Response Curves and Mean Spends by Channel using the Weibull CDF  in a one-pager format from raw data

### ISSUE THREAD

**Issue by k0he1h** [facebookexperimental/Robyn#885]
Hello everyone. 
We aim to replicate the Response Curves and Mean Spends by Channel using the Weibull CDF  in a one-pager format from raw data.
We believe that the adstock and decomp values from the pareto_media_transformation_matrix are essential for this figure. 
Based on previous discussions in GitHub, it seems that mean spends might be calculated using last month's adstock data. However, we're unable to replicate these values using this method. 
Could you please clarify the definition and necessary data for this?
Thank you for your help.

**Comment by gufengzhou** [comment]
Sorry for the late reply. There's been some back and forth on this. the idea of using last month was to better reflect the recent spend level, but it often leads to 0 values because not every channel is always on. Currently it's back to just the mean spend of the modelling window. The adstock calculation is bit complicated. If you want to dig the rabbit hole:

https://github.com/facebookexperimental/Robyn/blob/main/R/R/pareto.R#L179
