### ISSUE TITLE
Different results after running twice modeling 

### ISSUE THREAD

**Issue by wenyanyy** [facebookexperimental/Robyn#90]
Hi,

I found one question that there are different results of modelling after I run twice Robyn code. Could you tell me how to get fixed result? I understand it's randomly choose number for parameters but It's still a little bit confusing to get different results. I tried to set seed to fix the result but it doesn't work. Please tell me how to resolve it. Thanks a lot 

Best,
Regina

**Comment by gufengzhou** [comment]
Hey Regina, there's a piece of code in the session "## reload old models from csv" in the .exec script, which is for the use case to reproduce a set of selected hyperparameters from a csv. Can you try that out? Otherwise, Robyn always output a set of results, not one single result. Unless you reuse the exact same set of hyperparameters, it's unlikely to have exact the same results. setting seeds doesn't really play a role here
