### ISSUE TITLE
Linear vs multiplicative

### ISSUE THREAD

**Issue by retiuk** [facebookexperimental/Robyn#96]
Hi team,

What do you think about trying a multiplicative model instead of linear to capture synergy between channels? Is this something you have considered? Interested to hear your thoughts on that.

`family=gaussian(link="log")`

instead of

`family = "gaussian",`

Thanks,
R

**Comment by Leonelsentana** [comment]
Hey Retiuk,

Thanks for your interest in Robyn :) We have considered multiplicative models in the past. However, we aimed for easy-to-interpret and computing-efficient models. This is because democratizing, scaling and inspiring marketing models is our main goal. If you have a lot of variables and sub-variables (50 different FB, 50 different TV variables, 50 different affiliate variables, etc.), you get high-cardinality, a lot of multiplication and therefore computationally unreasonable models, which may collide with an easy-to-use, computationally-efficient and easy-to-interpret solution. Interaction terms are important insights and sometimes understanding correlations and covariance between channels and baseline variables are key to be able to understand better how each variable interacts with one another.

Hope it helps!
Thanks,
Leo
