### ISSUE TITLE
Error when adding factor variables in baseline section

### ISSUE THREAD

**Issue by ayundaril** [facebookexperimental/Robyn#99]
# Contributing to FB NextGen MMM R script

# Issue

Hello, I am having problem with the inclusion of factor/qualitative variables in the model. 
At the moment, the inclusion of factor variables in the baseline section throws an error when running the models.
Am I doing something wrong? Could you provide guidance as to the inclusion of factor/qualitative variables in models?
Thx!

# Steps to Reproduce

The following steps have been followed:
1. include one factor variables in baseline. Each factor variable is coded as a 0/1 binary variable
2. declare factor variables in "set_factorVarName"
3. dt_mod <- f.inputWrangling() runs smoothly and generates a (seemingly) correct dt_mod dataset. The factor variable has been stored as a "factor with 2 levels" variable.
4. run the model: model_output_collect <- f.robyn(...

# Expected Behavior

Models are run smoothly

# Actual Results

An error is displayed as: " Error in { : task 1 failed - "column(s) not found: Promo "
Estimation stops.

# Environment

R version (R --version)

**Comment by gufengzhou** [comment]
Hey, I assume Promo is your factor variable or how many factor vars do you have? can you share a screenshot of how the dt_mod looks like and the whole baseline/media/factor specification part in the execution script?

**Comment by ayundaril** [comment]
Hi. For the sake of privacy I would rather not show the names of the media variables, nor their values as they are real life values. I have, however, reproduced the same error by adding two factor variables to the demo data (de_simulated_data.csv).

Promo_1 and Promo_2 are two binary variables capturing periods in which each type of Promo was enabled (Value=1). Note that they could both be active at the same time.


Plese find below the baseline/media/factor specification part

activate_baseline <- T
set_baseVarName <- c("Promo_1", "Promo_2") 
set_baseVarSign <- c("default", "default")

set_mediaVarName <- c("tv_S"	,"ooh_S",	"print_S"	,"facebook_I"	,"search_clicks_P") 
set_mediaVarSign <- c("positive", "positive", "positive", "positive", "positive") 
set_mediaSpendName <- c("tv_S"	,"ooh_S",	"print_S"	,"facebook_S"	,"search_S") 

set_factorVarName <- c("Promo_1", "Promo_2") 

And a screenshot of the dt_mod (along with the error message I get once I run the models)
<img width="1138" alt="Screenshot 2021-07-02 at 13 34 38" src="https://user-images.githubusercontent.com/77012748/124268834-5d9ba680-db3a-11eb-921b-712e7db801d6.png">

**Comment by gufengzhou** [comment]
Hey, thank you very much for pointing this out. Indeed there's a bug in the f.decomp function that causes failures when using factorial variables. I'll fix this in the next release. Sorry for the inconvenience!

Until then, there's a work-around by using the "holiday" variable in prophet. When you look at the holidays.csv, you'll see all holidays for given countries included. You can see that this data.table includes all holidays from 1995 -2044. You can manually add your promotions as holidays into this table for your country, then run the script using the prophet holiday variable (and remove promo1 & 2 from baseline). This way, both promo effects will be included into/ treated as holiday. I know it's maybe not ideal because you might want to have them separated. But for now it helps you get initial results.

**Comment by gufengzhou** [comment]
let me know if you have other issues
